package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FltVisitesTechniques generated by hbm2java
 */
@Entity
@Table(name="flt_visites_techniques"
    ,catalog="ankata_db"
)
public class FltVisitesTechniques  implements java.io.Serializable {


     private Long id;
     private FltVehicules fltVehicules;
     private Integer annee;
     private Date dateVis;
     private Double montant;
     private String observation;

    public FltVisitesTechniques() {
    }

    public FltVisitesTechniques(FltVehicules fltVehicules, Integer annee, Date dateVis, Double montant, String observation) {
       this.fltVehicules = fltVehicules;
       this.annee = annee;
       this.dateVis = dateVis;
       this.montant = montant;
       this.observation = observation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicule")
    public FltVehicules getFltVehicules() {
        return this.fltVehicules;
    }
    
    public void setFltVehicules(FltVehicules fltVehicules) {
        this.fltVehicules = fltVehicules;
    }

    
    @Column(name="annee")
    public Integer getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(Integer annee) {
        this.annee = annee;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_vis", length=10)
    public Date getDateVis() {
        return this.dateVis;
    }
    
    public void setDateVis(Date dateVis) {
        this.dateVis = dateVis;
    }

    
    @Column(name="montant", precision=22, scale=0)
    public Double getMontant() {
        return this.montant;
    }
    
    public void setMontant(Double montant) {
        this.montant = montant;
    }

    
    @Column(name="observation")
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }




}


