package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.achat.AchBonsLivraisons;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StkMagasins generated by hbm2java
 */
@Entity
@Table(name="stk_magasins"
    ,catalog="ankata_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class StkMagasins  implements java.io.Serializable {


     private Long id;
     private String code;
     private String libelle;
     private Set<AchBonsLivraisons> achBonsLivraisonses = new HashSet<AchBonsLivraisons>(0);
     private Set<StkBonsCommandesInternes> stkBonsCommandesInterneses = new HashSet<StkBonsCommandesInternes>(0);
     private Set<StkBonsSorties> stkBonsSortieses = new HashSet<StkBonsSorties>(0);
     private Set<StkStocks> stkStockses = new HashSet<StkStocks>(0);
     private Set<StkInventaires> stkInventaireses = new HashSet<StkInventaires>(0);
     private Set<StkMagasinsArticles> stkMagasinsArticleses = new HashSet<StkMagasinsArticles>(0);

    public StkMagasins() {
    }

    public StkMagasins(String code, String libelle, Set<AchBonsLivraisons> achBonsLivraisonses, Set<StkBonsCommandesInternes> stkBonsCommandesInterneses, Set<StkBonsSorties> stkBonsSortieses, Set<StkStocks> stkStockses, Set<StkInventaires> stkInventaireses, Set<StkMagasinsArticles> stkMagasinsArticleses) {
       this.code = code;
       this.libelle = libelle;
       this.achBonsLivraisonses = achBonsLivraisonses;
       this.stkBonsCommandesInterneses = stkBonsCommandesInterneses;
       this.stkBonsSortieses = stkBonsSortieses;
       this.stkStockses = stkStockses;
       this.stkInventaireses = stkInventaireses;
       this.stkMagasinsArticleses = stkMagasinsArticleses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="code", unique=true, length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkMagasins")
    public Set<AchBonsLivraisons> getAchBonsLivraisonses() {
        return this.achBonsLivraisonses;
    }
    
    public void setAchBonsLivraisonses(Set<AchBonsLivraisons> achBonsLivraisonses) {
        this.achBonsLivraisonses = achBonsLivraisonses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkMagasins")
    public Set<StkBonsCommandesInternes> getStkBonsCommandesInterneses() {
        return this.stkBonsCommandesInterneses;
    }
    
    public void setStkBonsCommandesInterneses(Set<StkBonsCommandesInternes> stkBonsCommandesInterneses) {
        this.stkBonsCommandesInterneses = stkBonsCommandesInterneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkMagasins")
    public Set<StkBonsSorties> getStkBonsSortieses() {
        return this.stkBonsSortieses;
    }
    
    public void setStkBonsSortieses(Set<StkBonsSorties> stkBonsSortieses) {
        this.stkBonsSortieses = stkBonsSortieses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkMagasins")
    public Set<StkStocks> getStkStockses() {
        return this.stkStockses;
    }
    
    public void setStkStockses(Set<StkStocks> stkStockses) {
        this.stkStockses = stkStockses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkMagasins")
    public Set<StkInventaires> getStkInventaireses() {
        return this.stkInventaireses;
    }
    
    public void setStkInventaireses(Set<StkInventaires> stkInventaireses) {
        this.stkInventaireses = stkInventaireses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkMagasins")
    public Set<StkMagasinsArticles> getStkMagasinsArticleses() {
        return this.stkMagasinsArticleses;
    }
    
    public void setStkMagasinsArticleses(Set<StkMagasinsArticles> stkMagasinsArticleses) {
        this.stkMagasinsArticleses = stkMagasinsArticleses;
    }




}


