package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComClients;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FltReservation generated by hbm2java
 */
@Entity
@Table(name="flt_reservation"
    ,catalog="ankata_db"
)
public class FltReservation  implements java.io.Serializable {


     private long id;
     private ComClients comClients;
     private FltVehicules fltVehicules;
     private Date dateFin;
     private Date datedebut;
     private Double prix;

    public FltReservation() {
    }

	
    public FltReservation(long id, ComClients comClients, FltVehicules fltVehicules) {
        this.id = id;
        this.comClients = comClients;
        this.fltVehicules = fltVehicules;
    }
    public FltReservation(long id, ComClients comClients, FltVehicules fltVehicules, Date dateFin, Date datedebut, Double prix) {
       this.id = id;
       this.comClients = comClients;
       this.fltVehicules = fltVehicules;
       this.dateFin = dateFin;
       this.datedebut = datedebut;
       this.prix = prix;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="clients", nullable=false)
    public ComClients getComClients() {
        return this.comClients;
    }
    
    public void setComClients(ComClients comClients) {
        this.comClients = comClients;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicule", nullable=false)
    public FltVehicules getFltVehicules() {
        return this.fltVehicules;
    }
    
    public void setFltVehicules(FltVehicules fltVehicules) {
        this.fltVehicules = fltVehicules;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_fin", length=10)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datedebut", length=10)
    public Date getDatedebut() {
        return this.datedebut;
    }
    
    public void setDatedebut(Date datedebut) {
        this.datedebut = datedebut;
    }

    
    @Column(name="prix", precision=22, scale=0)
    public Double getPrix() {
        return this.prix;
    }
    
    public void setPrix(Double prix) {
        this.prix = prix;
    }




}


