package com.horus.ankata.core.domain.achat;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComFournisseurs;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AchBonsCommandes generated by hbm2java
 */
@Entity
@Table(name="ach_bons_commandes"
    ,catalog="ankata_db"
)
public class AchBonsCommandes  implements java.io.Serializable {


     private Long id;
     private AchDevis achDevis;
     private ComFournisseurs comFournisseurs;
     private Date dateBon;
     private Date dateLivSouhaite;
     private String description;
     private Integer etat;
     private Double montantHt;
     private Double montantTtc;
     private Double montantTva;
     private String numBon;
     private Double tva;
     private Set<AchBonsLivraisons> achBonsLivraisonses = new HashSet<AchBonsLivraisons>(0);
     private Set<AchBonsCommandesLignes> achBonsCommandesLigneses = new HashSet<AchBonsCommandesLignes>(0);

    public AchBonsCommandes() {
    }

    public AchBonsCommandes(AchDevis achDevis, ComFournisseurs comFournisseurs, Date dateBon, Date dateLivSouhaite, String description, Integer etat, Double montantHt, Double montantTtc, Double montantTva, String numBon, Double tva, Set<AchBonsLivraisons> achBonsLivraisonses, Set<AchBonsCommandesLignes> achBonsCommandesLigneses) {
       this.achDevis = achDevis;
       this.comFournisseurs = comFournisseurs;
       this.dateBon = dateBon;
       this.dateLivSouhaite = dateLivSouhaite;
       this.description = description;
       this.etat = etat;
       this.montantHt = montantHt;
       this.montantTtc = montantTtc;
       this.montantTva = montantTva;
       this.numBon = numBon;
       this.tva = tva;
       this.achBonsLivraisonses = achBonsLivraisonses;
       this.achBonsCommandesLigneses = achBonsCommandesLigneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="devis")
    public AchDevis getAchDevis() {
        return this.achDevis;
    }
    
    public void setAchDevis(AchDevis achDevis) {
        this.achDevis = achDevis;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="founisseur")
    public ComFournisseurs getComFournisseurs() {
        return this.comFournisseurs;
    }
    
    public void setComFournisseurs(ComFournisseurs comFournisseurs) {
        this.comFournisseurs = comFournisseurs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_bon", length=10)
    public Date getDateBon() {
        return this.dateBon;
    }
    
    public void setDateBon(Date dateBon) {
        this.dateBon = dateBon;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_liv_souhaite", length=10)
    public Date getDateLivSouhaite() {
        return this.dateLivSouhaite;
    }
    
    public void setDateLivSouhaite(Date dateLivSouhaite) {
        this.dateLivSouhaite = dateLivSouhaite;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="etat")
    public Integer getEtat() {
        return this.etat;
    }
    
    public void setEtat(Integer etat) {
        this.etat = etat;
    }

    
    @Column(name="montant_ht", precision=22, scale=0)
    public Double getMontantHt() {
        return this.montantHt;
    }
    
    public void setMontantHt(Double montantHt) {
        this.montantHt = montantHt;
    }

    
    @Column(name="montant_ttc", precision=22, scale=0)
    public Double getMontantTtc() {
        return this.montantTtc;
    }
    
    public void setMontantTtc(Double montantTtc) {
        this.montantTtc = montantTtc;
    }

    
    @Column(name="montant_tva", precision=22, scale=0)
    public Double getMontantTva() {
        return this.montantTva;
    }
    
    public void setMontantTva(Double montantTva) {
        this.montantTva = montantTva;
    }

    
    @Column(name="num_bon", length=20)
    public String getNumBon() {
        return this.numBon;
    }
    
    public void setNumBon(String numBon) {
        this.numBon = numBon;
    }

    
    @Column(name="tva", precision=22, scale=0)
    public Double getTva() {
        return this.tva;
    }
    
    public void setTva(Double tva) {
        this.tva = tva;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="achBonsCommandes")
    public Set<AchBonsLivraisons> getAchBonsLivraisonses() {
        return this.achBonsLivraisonses;
    }
    
    public void setAchBonsLivraisonses(Set<AchBonsLivraisons> achBonsLivraisonses) {
        this.achBonsLivraisonses = achBonsLivraisonses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="achBonsCommandes")
    public Set<AchBonsCommandesLignes> getAchBonsCommandesLigneses() {
        return this.achBonsCommandesLigneses;
    }
    
    public void setAchBonsCommandesLigneses(Set<AchBonsCommandesLignes> achBonsCommandesLigneses) {
        this.achBonsCommandesLigneses = achBonsCommandesLigneses;
    }




}


