package com.horus.ankata.core.domain.vente;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComBanques;
import com.horus.ankata.core.domain.commons.ComCaisses;
import com.horus.ankata.core.domain.commons.ComTypesPayements;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VteBonsEncaissements generated by hbm2java
 */
@Entity
@Table(name="vte_bons_encaissements"
    ,catalog="ankata_db"
)
public class VteBonsEncaissements  implements java.io.Serializable {


     private Long id;
     private ComBanques comBanques;
     private ComCaisses comCaisses;
     private ComTypesPayements comTypesPayements;
     private VteFactures vteFactures;
     private Date dateEncaissement;
     private Date datePaiement;
     private Byte etat;
     private Double montantTtc;
     private String numBon;
     private String numCheque;
     private String origine;
     private String recouvrement;
     private String refDoc;

    public VteBonsEncaissements() {
    }

    public VteBonsEncaissements(ComBanques comBanques, ComCaisses comCaisses, ComTypesPayements comTypesPayements, VteFactures vteFactures, Date dateEncaissement, Date datePaiement, Byte etat, Double montantTtc, String numBon, String numCheque, String origine, String recouvrement, String refDoc) {
       this.comBanques = comBanques;
       this.comCaisses = comCaisses;
       this.comTypesPayements = comTypesPayements;
       this.vteFactures = vteFactures;
       this.dateEncaissement = dateEncaissement;
       this.datePaiement = datePaiement;
       this.etat = etat;
       this.montantTtc = montantTtc;
       this.numBon = numBon;
       this.numCheque = numCheque;
       this.origine = origine;
       this.recouvrement = recouvrement;
       this.refDoc = refDoc;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="banque")
    public ComBanques getComBanques() {
        return this.comBanques;
    }
    
    public void setComBanques(ComBanques comBanques) {
        this.comBanques = comBanques;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="caisse")
    public ComCaisses getComCaisses() {
        return this.comCaisses;
    }
    
    public void setComCaisses(ComCaisses comCaisses) {
        this.comCaisses = comCaisses;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mode_paiement")
    public ComTypesPayements getComTypesPayements() {
        return this.comTypesPayements;
    }
    
    public void setComTypesPayements(ComTypesPayements comTypesPayements) {
        this.comTypesPayements = comTypesPayements;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="facture")
    public VteFactures getVteFactures() {
        return this.vteFactures;
    }
    
    public void setVteFactures(VteFactures vteFactures) {
        this.vteFactures = vteFactures;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_encaissement", length=10)
    public Date getDateEncaissement() {
        return this.dateEncaissement;
    }
    
    public void setDateEncaissement(Date dateEncaissement) {
        this.dateEncaissement = dateEncaissement;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_paiement", length=10)
    public Date getDatePaiement() {
        return this.datePaiement;
    }
    
    public void setDatePaiement(Date datePaiement) {
        this.datePaiement = datePaiement;
    }

    
    @Column(name="etat")
    public Byte getEtat() {
        return this.etat;
    }
    
    public void setEtat(Byte etat) {
        this.etat = etat;
    }

    
    @Column(name="montant_ttc", precision=22, scale=0)
    public Double getMontantTtc() {
        return this.montantTtc;
    }
    
    public void setMontantTtc(Double montantTtc) {
        this.montantTtc = montantTtc;
    }

    
    @Column(name="num_bon", length=45)
    public String getNumBon() {
        return this.numBon;
    }
    
    public void setNumBon(String numBon) {
        this.numBon = numBon;
    }

    
    @Column(name="num_cheque", length=45)
    public String getNumCheque() {
        return this.numCheque;
    }
    
    public void setNumCheque(String numCheque) {
        this.numCheque = numCheque;
    }

    
    @Column(name="origine", length=3)
    public String getOrigine() {
        return this.origine;
    }
    
    public void setOrigine(String origine) {
        this.origine = origine;
    }

    
    @Column(name="recouvrement", length=200)
    public String getRecouvrement() {
        return this.recouvrement;
    }
    
    public void setRecouvrement(String recouvrement) {
        this.recouvrement = recouvrement;
    }

    
    @Column(name="ref_doc", length=45)
    public String getRefDoc() {
        return this.refDoc;
    }
    
    public void setRefDoc(String refDoc) {
        this.refDoc = refDoc;
    }




}


