package com.horus.ankata.core.domain.vente;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComProduits;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VteBonsLivraisonsLignes generated by hbm2java
 */
@Entity
@Table(name="vte_bons_livraisons_lignes"
    ,catalog="ankata_db"
)
public class VteBonsLivraisonsLignes  implements java.io.Serializable {


     private Long id;
     private ComProduits comProduits;
     private VteBonsLivraisons vteBonsLivraisons;
     private String libelle;
     private Integer qte;
     private Integer qteLivre;
     private String unite;

    public VteBonsLivraisonsLignes() {
    }

    public VteBonsLivraisonsLignes(ComProduits comProduits, VteBonsLivraisons vteBonsLivraisons, String libelle, Integer qte, Integer qteLivre, String unite) {
       this.comProduits = comProduits;
       this.vteBonsLivraisons = vteBonsLivraisons;
       this.libelle = libelle;
       this.qte = qte;
       this.qteLivre = qteLivre;
       this.unite = unite;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="produit")
    public ComProduits getComProduits() {
        return this.comProduits;
    }
    
    public void setComProduits(ComProduits comProduits) {
        this.comProduits = comProduits;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bon")
    public VteBonsLivraisons getVteBonsLivraisons() {
        return this.vteBonsLivraisons;
    }
    
    public void setVteBonsLivraisons(VteBonsLivraisons vteBonsLivraisons) {
        this.vteBonsLivraisons = vteBonsLivraisons;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="qte")
    public Integer getQte() {
        return this.qte;
    }
    
    public void setQte(Integer qte) {
        this.qte = qte;
    }

    
    @Column(name="qte_livre")
    public Integer getQteLivre() {
        return this.qteLivre;
    }
    
    public void setQteLivre(Integer qteLivre) {
        this.qteLivre = qteLivre;
    }

    
    @Column(name="unite", length=10)
    public String getUnite() {
        return this.unite;
    }
    
    public void setUnite(String unite) {
        this.unite = unite;
    }




}


