package com.horus.ankata.core.domain.vente;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VteDevisLignes generated by hbm2java
 */
@Entity
@Table(name="vte_devis_lignes"
    ,catalog="ankata_db"
)
public class VteDevisLignes  implements java.io.Serializable {


     private long id;
     private VteDevis vteDevis;
     private Date dateCharge;
     private String description;
     private String itneraire;
     private Double montantHt;
     private String nature;
     private String numBordoreau;
     private Double pu;
     private Double qte;

    public VteDevisLignes() {
    }

	
    public VteDevisLignes(long id) {
        this.id = id;
    }
    public VteDevisLignes(long id, VteDevis vteDevis, Date dateCharge, String description, String itneraire, Double montantHt, String nature, String numBordoreau, Double pu, Double qte) {
       this.id = id;
       this.vteDevis = vteDevis;
       this.dateCharge = dateCharge;
       this.description = description;
       this.itneraire = itneraire;
       this.montantHt = montantHt;
       this.nature = nature;
       this.numBordoreau = numBordoreau;
       this.pu = pu;
       this.qte = qte;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="devis")
    public VteDevis getVteDevis() {
        return this.vteDevis;
    }
    
    public void setVteDevis(VteDevis vteDevis) {
        this.vteDevis = vteDevis;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_charge", length=10)
    public Date getDateCharge() {
        return this.dateCharge;
    }
    
    public void setDateCharge(Date dateCharge) {
        this.dateCharge = dateCharge;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="itneraire", length=200)
    public String getItneraire() {
        return this.itneraire;
    }
    
    public void setItneraire(String itneraire) {
        this.itneraire = itneraire;
    }

    
    @Column(name="montant_ht", precision=22, scale=0)
    public Double getMontantHt() {
        return this.montantHt;
    }
    
    public void setMontantHt(Double montantHt) {
        this.montantHt = montantHt;
    }

    
    @Column(name="nature", length=45)
    public String getNature() {
        return this.nature;
    }
    
    public void setNature(String nature) {
        this.nature = nature;
    }

    
    @Column(name="num_bordoreau", length=45)
    public String getNumBordoreau() {
        return this.numBordoreau;
    }
    
    public void setNumBordoreau(String numBordoreau) {
        this.numBordoreau = numBordoreau;
    }

    
    @Column(name="pu", precision=22, scale=0)
    public Double getPu() {
        return this.pu;
    }
    
    public void setPu(Double pu) {
        this.pu = pu;
    }

    
    @Column(name="qte", precision=22, scale=0)
    public Double getQte() {
        return this.qte;
    }
    
    public void setQte(Double qte) {
        this.qte = qte;
    }




}


