package com.horus.ankata.core.domain.vente;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComClients;
import com.horus.ankata.core.domain.commons.ComTypesPayements;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VteDevis generated by hbm2java
 */
@Entity
@Table(name="vte_devis"
    ,catalog="ankata_db"
)
public class VteDevis  implements java.io.Serializable {


     private long id;
     private ComClients comClients;
     private ComTypesPayements comTypesPayements;
     private Date dateDevis;
     private String refDevis;
     private Double tva;
     private Set<VteDevisLignes> vteDevisLigneses = new HashSet<VteDevisLignes>(0);

    public VteDevis() {
    }

	
    public VteDevis(long id) {
        this.id = id;
    }
    public VteDevis(long id, ComClients comClients, ComTypesPayements comTypesPayements, Date dateDevis, String refDevis, Double tva, Set<VteDevisLignes> vteDevisLigneses) {
       this.id = id;
       this.comClients = comClients;
       this.comTypesPayements = comTypesPayements;
       this.dateDevis = dateDevis;
       this.refDevis = refDevis;
       this.tva = tva;
       this.vteDevisLigneses = vteDevisLigneses;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client")
    public ComClients getComClients() {
        return this.comClients;
    }
    
    public void setComClients(ComClients comClients) {
        this.comClients = comClients;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_payement")
    public ComTypesPayements getComTypesPayements() {
        return this.comTypesPayements;
    }
    
    public void setComTypesPayements(ComTypesPayements comTypesPayements) {
        this.comTypesPayements = comTypesPayements;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_devis", length=10)
    public Date getDateDevis() {
        return this.dateDevis;
    }
    
    public void setDateDevis(Date dateDevis) {
        this.dateDevis = dateDevis;
    }

    
    @Column(name="ref_devis", length=45)
    public String getRefDevis() {
        return this.refDevis;
    }
    
    public void setRefDevis(String refDevis) {
        this.refDevis = refDevis;
    }

    
    @Column(name="tva", precision=22, scale=0)
    public Double getTva() {
        return this.tva;
    }
    
    public void setTva(Double tva) {
        this.tva = tva;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vteDevis")
    public Set<VteDevisLignes> getVteDevisLigneses() {
        return this.vteDevisLigneses;
    }
    
    public void setVteDevisLigneses(Set<VteDevisLignes> vteDevisLigneses) {
        this.vteDevisLigneses = vteDevisLigneses;
    }




}


