package com.horus.ankata.core.domain.vente;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.flotte.FltMissions;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VteFacturesLignes generated by hbm2java
 */
@Entity
@Table(name="vte_factures_lignes"
    ,catalog="ankata_db"
)
public class VteFacturesLignes  implements java.io.Serializable {


     private Long id;
     private FltMissions fltMissions;
     private VteFactures vteFactures;
     private String libelle;
     private Double montantHt;
     private Double pu;
     private Double qte;
     private String refProd;

    public VteFacturesLignes() {
    }

    public VteFacturesLignes(FltMissions fltMissions, VteFactures vteFactures, String libelle, Double montantHt, Double pu, Double qte, String refProd) {
       this.fltMissions = fltMissions;
       this.vteFactures = vteFactures;
       this.libelle = libelle;
       this.montantHt = montantHt;
       this.pu = pu;
       this.qte = qte;
       this.refProd = refProd;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mission")
    public FltMissions getFltMissions() {
        return this.fltMissions;
    }
    
    public void setFltMissions(FltMissions fltMissions) {
        this.fltMissions = fltMissions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="facture")
    public VteFactures getVteFactures() {
        return this.vteFactures;
    }
    
    public void setVteFactures(VteFactures vteFactures) {
        this.vteFactures = vteFactures;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="montant_ht", precision=22, scale=0)
    public Double getMontantHt() {
        return this.montantHt;
    }
    
    public void setMontantHt(Double montantHt) {
        this.montantHt = montantHt;
    }

    
    @Column(name="pu", precision=22, scale=0)
    public Double getPu() {
        return this.pu;
    }
    
    public void setPu(Double pu) {
        this.pu = pu;
    }

    
    @Column(name="qte", precision=22, scale=0)
    public Double getQte() {
        return this.qte;
    }
    
    public void setQte(Double qte) {
        this.qte = qte;
    }

    
    @Column(name="ref_prod", length=45)
    public String getRefProd() {
        return this.refProd;
    }
    
    public void setRefProd(String refProd) {
        this.refProd = refProd;
    }




}


