package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FltTypesInfractions generated by hbm2java
 */
@Entity
@Table(name="flt_types_infractions"
    ,catalog="ankata_db"
)
public class FltTypesInfractions  implements java.io.Serializable {


     private Long id;
     private String libelle;
     private Set<FltMissionsInfractions> fltMissionsInfractionses = new HashSet<FltMissionsInfractions>(0);

    public FltTypesInfractions() {
    }

    public FltTypesInfractions(String libelle, Set<FltMissionsInfractions> fltMissionsInfractionses) {
       this.libelle = libelle;
       this.fltMissionsInfractionses = fltMissionsInfractionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltTypesInfractions")
    public Set<FltMissionsInfractions> getFltMissionsInfractionses() {
        return this.fltMissionsInfractionses;
    }
    
    public void setFltMissionsInfractionses(Set<FltMissionsInfractions> fltMissionsInfractionses) {
        this.fltMissionsInfractionses = fltMissionsInfractionses;
    }




}


