package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComCivilites generated by hbm2java
 */
@Entity
@Table(name="com_civilites"
    ,catalog="ankata_db"
)
public class ComCivilites  implements java.io.Serializable {


     private String code;
     private String libelle;
     private Set<ComPersonnes> comPersonneses = new HashSet<ComPersonnes>(0);

    public ComCivilites() {
    }

	
    public ComCivilites(String code) {
        this.code = code;
    }
    public ComCivilites(String code, String libelle, Set<ComPersonnes> comPersonneses) {
       this.code = code;
       this.libelle = libelle;
       this.comPersonneses = comPersonneses;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=5)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comCivilites")
    public Set<ComPersonnes> getComPersonneses() {
        return this.comPersonneses;
    }
    
    public void setComPersonneses(Set<ComPersonnes> comPersonneses) {
        this.comPersonneses = comPersonneses;
    }




}


