package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FltAssurances generated by hbm2java
 */
@Entity
@Table(name="flt_assurances"
    ,catalog="ankata_db"
)
public class FltAssurances  implements java.io.Serializable {


     private Long id;
     private FltAssurancesComp fltAssurancesComp;
     private FltVehicules fltVehicules;
     private Date dateDeb;
     private Date dateFin;
     private String numAttestation;
     private String numPolice;

    public FltAssurances() {
    }

    public FltAssurances(FltAssurancesComp fltAssurancesComp, FltVehicules fltVehicules, Date dateDeb, Date dateFin, String numAttestation, String numPolice) {
       this.fltAssurancesComp = fltAssurancesComp;
       this.fltVehicules = fltVehicules;
       this.dateDeb = dateDeb;
       this.dateFin = dateFin;
       this.numAttestation = numAttestation;
       this.numPolice = numPolice;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="compagnie")
    public FltAssurancesComp getFltAssurancesComp() {
        return this.fltAssurancesComp;
    }
    
    public void setFltAssurancesComp(FltAssurancesComp fltAssurancesComp) {
        this.fltAssurancesComp = fltAssurancesComp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicule")
    public FltVehicules getFltVehicules() {
        return this.fltVehicules;
    }
    
    public void setFltVehicules(FltVehicules fltVehicules) {
        this.fltVehicules = fltVehicules;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_deb", length=19)
    public Date getDateDeb() {
        return this.dateDeb;
    }
    
    public void setDateDeb(Date dateDeb) {
        this.dateDeb = dateDeb;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_fin", length=19)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    
    @Column(name="num_attestation", length=20)
    public String getNumAttestation() {
        return this.numAttestation;
    }
    
    public void setNumAttestation(String numAttestation) {
        this.numAttestation = numAttestation;
    }

    
    @Column(name="num_police", length=20)
    public String getNumPolice() {
        return this.numPolice;
    }
    
    public void setNumPolice(String numPolice) {
        this.numPolice = numPolice;
    }




}


