package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StkArticlesChamps generated by hbm2java
 */
@Entity
@Table(name="stk_articles_champs"
    ,catalog="ankata_db"
)
public class StkArticlesChamps  implements java.io.Serializable {


     private Long id;
     private StkArticles stkArticles;
     private StkArticlesFamillesChamps stkArticlesFamillesChamps;
     private String valeur;

    public StkArticlesChamps() {
    }

    public StkArticlesChamps(StkArticles stkArticles, StkArticlesFamillesChamps stkArticlesFamillesChamps, String valeur) {
       this.stkArticles = stkArticles;
       this.stkArticlesFamillesChamps = stkArticlesFamillesChamps;
       this.valeur = valeur;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="article")
    public StkArticles getStkArticles() {
        return this.stkArticles;
    }
    
    public void setStkArticles(StkArticles stkArticles) {
        this.stkArticles = stkArticles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="champ")
    public StkArticlesFamillesChamps getStkArticlesFamillesChamps() {
        return this.stkArticlesFamillesChamps;
    }
    
    public void setStkArticlesFamillesChamps(StkArticlesFamillesChamps stkArticlesFamillesChamps) {
        this.stkArticlesFamillesChamps = stkArticlesFamillesChamps;
    }

    
    @Column(name="valeur")
    public String getValeur() {
        return this.valeur;
    }
    
    public void setValeur(String valeur) {
        this.valeur = valeur;
    }




}


