package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StkArticlesFamilles generated by hbm2java
 */
@Entity
@Table(name="stk_articles_familles"
    ,catalog="ankata_db"
)
public class StkArticlesFamilles  implements java.io.Serializable {


     private Long id;
     private String nom;
     private Set<StkArticlesFamillesChamps> stkArticlesFamillesChampses = new HashSet<StkArticlesFamillesChamps>(0);
     private Set<StkArticles> stkArticleses = new HashSet<StkArticles>(0);

    public StkArticlesFamilles() {
    }

    public StkArticlesFamilles(String nom, Set<StkArticlesFamillesChamps> stkArticlesFamillesChampses, Set<StkArticles> stkArticleses) {
       this.nom = nom;
       this.stkArticlesFamillesChampses = stkArticlesFamillesChampses;
       this.stkArticleses = stkArticleses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="nom", length=200)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticlesFamilles")
    public Set<StkArticlesFamillesChamps> getStkArticlesFamillesChampses() {
        return this.stkArticlesFamillesChampses;
    }
    
    public void setStkArticlesFamillesChampses(Set<StkArticlesFamillesChamps> stkArticlesFamillesChampses) {
        this.stkArticlesFamillesChampses = stkArticlesFamillesChampses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticlesFamilles")
    public Set<StkArticles> getStkArticleses() {
        return this.stkArticleses;
    }
    
    public void setStkArticleses(Set<StkArticles> stkArticleses) {
        this.stkArticleses = stkArticleses;
    }




}


