package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.achat.*;
import com.horus.ankata.core.domain.commons.ComUnites;
import com.horus.ankata.core.domain.flotte.FltDdesInvsPieces;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StkArticles generated by hbm2java
 */
@Entity
@Table(name="stk_articles"
    ,catalog="ankata_db"
)
public class StkArticles  implements java.io.Serializable {


     private Long id;
     private ComUnites comUnites;
     private StkArticlesFamilles stkArticlesFamilles;
     private String barecode;
     private String code;
     private Date dateAjout;
     private String nom;
     private String note;
     private String photo;
     private Double pump;
     private String qrcode;
     private Double qteDispo;
     private Double qteEntree;
     private Double qteReelle;
     private Double qteSortie;
     private Double stockAlert;
     private Double stockInitial;
     private Double stockMax;
     private Double stockMini;
     private Double tva;
     private Set<AchFacturesLignes> achFacturesLigneses = new HashSet<AchFacturesLignes>(0);
     private Set<StkMagasinsArticles> stkMagasinsArticleses = new HashSet<StkMagasinsArticles>(0);
     private Set<AchDevisLignes> achDevisLigneses = new HashSet<AchDevisLignes>(0);
     private Set<AchBonsLivraisonsLignes> achBonsLivraisonsLigneses = new HashSet<AchBonsLivraisonsLignes>(0);
     private Set<StkArticlesChamps> stkArticlesChampses = new HashSet<StkArticlesChamps>(0);
     private Set<AchBonsCommandesLignes> achBonsCommandesLigneses = new HashSet<AchBonsCommandesLignes>(0);
     private Set<AchDemandesLignes> achDemandesLigneses = new HashSet<AchDemandesLignes>(0);
     private Set<StkStocks> stkStockses = new HashSet<StkStocks>(0);
     private Set<FltDdesInvsPieces> fltDdesInvsPieceses = new HashSet<FltDdesInvsPieces>(0);
     private Set<StkBonsSortiesLignes> stkBonsSortiesLigneses = new HashSet<StkBonsSortiesLignes>(0);

    public StkArticles() {
    }

    public StkArticles(ComUnites comUnites, StkArticlesFamilles stkArticlesFamilles, String barecode, String code, Date dateAjout, String nom, String note, String photo, Double pump, String qrcode, Double qteDispo, Double qteEntree, Double qteReelle, Double qteSortie, Double stockAlert, Double stockInitial, Double stockMax, Double stockMini, Double tva, Set<AchFacturesLignes> achFacturesLigneses, Set<StkMagasinsArticles> stkMagasinsArticleses, Set<AchDevisLignes> achDevisLigneses, Set<AchBonsLivraisonsLignes> achBonsLivraisonsLigneses, Set<StkArticlesChamps> stkArticlesChampses, Set<AchBonsCommandesLignes> achBonsCommandesLigneses, Set<AchDemandesLignes> achDemandesLigneses, Set<StkStocks> stkStockses, Set<FltDdesInvsPieces> fltDdesInvsPieceses, Set<StkBonsSortiesLignes> stkBonsSortiesLigneses) {
       this.comUnites = comUnites;
       this.stkArticlesFamilles = stkArticlesFamilles;
       this.barecode = barecode;
       this.code = code;
       this.dateAjout = dateAjout;
       this.nom = nom;
       this.note = note;
       this.photo = photo;
       this.pump = pump;
       this.qrcode = qrcode;
       this.qteDispo = qteDispo;
       this.qteEntree = qteEntree;
       this.qteReelle = qteReelle;
       this.qteSortie = qteSortie;
       this.stockAlert = stockAlert;
       this.stockInitial = stockInitial;
       this.stockMax = stockMax;
       this.stockMini = stockMini;
       this.tva = tva;
       this.achFacturesLigneses = achFacturesLigneses;
       this.stkMagasinsArticleses = stkMagasinsArticleses;
       this.achDevisLigneses = achDevisLigneses;
       this.achBonsLivraisonsLigneses = achBonsLivraisonsLigneses;
       this.stkArticlesChampses = stkArticlesChampses;
       this.achBonsCommandesLigneses = achBonsCommandesLigneses;
       this.achDemandesLigneses = achDemandesLigneses;
       this.stkStockses = stkStockses;
       this.fltDdesInvsPieceses = fltDdesInvsPieceses;
       this.stkBonsSortiesLigneses = stkBonsSortiesLigneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unite")
    public ComUnites getComUnites() {
        return this.comUnites;
    }
    
    public void setComUnites(ComUnites comUnites) {
        this.comUnites = comUnites;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="famille")
    public StkArticlesFamilles getStkArticlesFamilles() {
        return this.stkArticlesFamilles;
    }
    
    public void setStkArticlesFamilles(StkArticlesFamilles stkArticlesFamilles) {
        this.stkArticlesFamilles = stkArticlesFamilles;
    }

    
    @Column(name="barecode", length=200)
    public String getBarecode() {
        return this.barecode;
    }
    
    public void setBarecode(String barecode) {
        this.barecode = barecode;
    }

    
    @Column(name="code", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_ajout", length=10)
    public Date getDateAjout() {
        return this.dateAjout;
    }
    
    public void setDateAjout(Date dateAjout) {
        this.dateAjout = dateAjout;
    }

    
    @Column(name="nom", length=200)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="note")
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="photo", length=20)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="pump", precision=22, scale=0)
    public Double getPump() {
        return this.pump;
    }
    
    public void setPump(Double pump) {
        this.pump = pump;
    }

    
    @Column(name="qrcode", length=200)
    public String getQrcode() {
        return this.qrcode;
    }
    
    public void setQrcode(String qrcode) {
        this.qrcode = qrcode;
    }

    
    @Column(name="qte_dispo", precision=22, scale=0)
    public Double getQteDispo() {
        return this.qteDispo;
    }
    
    public void setQteDispo(Double qteDispo) {
        this.qteDispo = qteDispo;
    }

    
    @Column(name="qte_entree", precision=22, scale=0)
    public Double getQteEntree() {
        return this.qteEntree;
    }
    
    public void setQteEntree(Double qteEntree) {
        this.qteEntree = qteEntree;
    }

    
    @Column(name="qte_reelle", precision=22, scale=0)
    public Double getQteReelle() {
        return this.qteReelle;
    }
    
    public void setQteReelle(Double qteReelle) {
        this.qteReelle = qteReelle;
    }

    
    @Column(name="qte_sortie", precision=22, scale=0)
    public Double getQteSortie() {
        return this.qteSortie;
    }
    
    public void setQteSortie(Double qteSortie) {
        this.qteSortie = qteSortie;
    }

    
    @Column(name="stock_alert", precision=22, scale=0)
    public Double getStockAlert() {
        return this.stockAlert;
    }
    
    public void setStockAlert(Double stockAlert) {
        this.stockAlert = stockAlert;
    }

    
    @Column(name="stock_initial", precision=22, scale=0)
    public Double getStockInitial() {
        return this.stockInitial;
    }
    
    public void setStockInitial(Double stockInitial) {
        this.stockInitial = stockInitial;
    }

    
    @Column(name="stock_max", precision=22, scale=0)
    public Double getStockMax() {
        return this.stockMax;
    }
    
    public void setStockMax(Double stockMax) {
        this.stockMax = stockMax;
    }

    
    @Column(name="stock_mini", precision=22, scale=0)
    public Double getStockMini() {
        return this.stockMini;
    }
    
    public void setStockMini(Double stockMini) {
        this.stockMini = stockMini;
    }

    
    @Column(name="tva", precision=22, scale=0)
    public Double getTva() {
        return this.tva;
    }
    
    public void setTva(Double tva) {
        this.tva = tva;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticles")
    public Set<AchFacturesLignes> getAchFacturesLigneses() {
        return this.achFacturesLigneses;
    }
    
    public void setAchFacturesLigneses(Set<AchFacturesLignes> achFacturesLigneses) {
        this.achFacturesLigneses = achFacturesLigneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticles")
    public Set<StkMagasinsArticles> getStkMagasinsArticleses() {
        return this.stkMagasinsArticleses;
    }
    
    public void setStkMagasinsArticleses(Set<StkMagasinsArticles> stkMagasinsArticleses) {
        this.stkMagasinsArticleses = stkMagasinsArticleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticles")
    public Set<AchDevisLignes> getAchDevisLigneses() {
        return this.achDevisLigneses;
    }
    
    public void setAchDevisLigneses(Set<AchDevisLignes> achDevisLigneses) {
        this.achDevisLigneses = achDevisLigneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticles")
    public Set<AchBonsLivraisonsLignes> getAchBonsLivraisonsLigneses() {
        return this.achBonsLivraisonsLigneses;
    }
    
    public void setAchBonsLivraisonsLigneses(Set<AchBonsLivraisonsLignes> achBonsLivraisonsLigneses) {
        this.achBonsLivraisonsLigneses = achBonsLivraisonsLigneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticles")
    public Set<StkArticlesChamps> getStkArticlesChampses() {
        return this.stkArticlesChampses;
    }
    
    public void setStkArticlesChampses(Set<StkArticlesChamps> stkArticlesChampses) {
        this.stkArticlesChampses = stkArticlesChampses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticles")
    public Set<AchBonsCommandesLignes> getAchBonsCommandesLigneses() {
        return this.achBonsCommandesLigneses;
    }
    
    public void setAchBonsCommandesLigneses(Set<AchBonsCommandesLignes> achBonsCommandesLigneses) {
        this.achBonsCommandesLigneses = achBonsCommandesLigneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticles")
    public Set<AchDemandesLignes> getAchDemandesLigneses() {
        return this.achDemandesLigneses;
    }
    
    public void setAchDemandesLigneses(Set<AchDemandesLignes> achDemandesLigneses) {
        this.achDemandesLigneses = achDemandesLigneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticles")
    public Set<StkStocks> getStkStockses() {
        return this.stkStockses;
    }
    
    public void setStkStockses(Set<StkStocks> stkStockses) {
        this.stkStockses = stkStockses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticles")
    public Set<FltDdesInvsPieces> getFltDdesInvsPieceses() {
        return this.fltDdesInvsPieceses;
    }
    
    public void setFltDdesInvsPieceses(Set<FltDdesInvsPieces> fltDdesInvsPieceses) {
        this.fltDdesInvsPieceses = fltDdesInvsPieceses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticles")
    public Set<StkBonsSortiesLignes> getStkBonsSortiesLigneses() {
        return this.stkBonsSortiesLigneses;
    }
    
    public void setStkBonsSortiesLigneses(Set<StkBonsSortiesLignes> stkBonsSortiesLigneses) {
        this.stkBonsSortiesLigneses = stkBonsSortiesLigneses;
    }




}


