package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.flotte.FltVehicules;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StkBonsCommandesInternes generated by hbm2java
 */
@Entity
@Table(name="stk_bons_commandes_internes"
    ,catalog="ankata_db"
)
public class StkBonsCommandesInternes  implements java.io.Serializable {


     private Long id;
     private FltVehicules fltVehicules;
     private StkMagasins stkMagasins;
     private Date dateBon;
     private String description;
     private Long diagnostic;
     private Integer etat;
     private String numBon;
     private Set<StkBonsSorties> stkBonsSortieses = new HashSet<StkBonsSorties>(0);

    public StkBonsCommandesInternes() {
    }

    public StkBonsCommandesInternes(FltVehicules fltVehicules, StkMagasins stkMagasins, Date dateBon, String description, Long diagnostic, Integer etat, String numBon, Set<StkBonsSorties> stkBonsSortieses) {
       this.fltVehicules = fltVehicules;
       this.stkMagasins = stkMagasins;
       this.dateBon = dateBon;
       this.description = description;
       this.diagnostic = diagnostic;
       this.etat = etat;
       this.numBon = numBon;
       this.stkBonsSortieses = stkBonsSortieses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicule")
    public FltVehicules getFltVehicules() {
        return this.fltVehicules;
    }
    
    public void setFltVehicules(FltVehicules fltVehicules) {
        this.fltVehicules = fltVehicules;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="magasin")
    public StkMagasins getStkMagasins() {
        return this.stkMagasins;
    }
    
    public void setStkMagasins(StkMagasins stkMagasins) {
        this.stkMagasins = stkMagasins;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_bon", length=10)
    public Date getDateBon() {
        return this.dateBon;
    }
    
    public void setDateBon(Date dateBon) {
        this.dateBon = dateBon;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="diagnostic")
    public Long getDiagnostic() {
        return this.diagnostic;
    }
    
    public void setDiagnostic(Long diagnostic) {
        this.diagnostic = diagnostic;
    }

    
    @Column(name="etat")
    public Integer getEtat() {
        return this.etat;
    }
    
    public void setEtat(Integer etat) {
        this.etat = etat;
    }

    
    @Column(name="num_bon", length=20)
    public String getNumBon() {
        return this.numBon;
    }
    
    public void setNumBon(String numBon) {
        this.numBon = numBon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkBonsCommandesInternes")
    public Set<StkBonsSorties> getStkBonsSortieses() {
        return this.stkBonsSortieses;
    }
    
    public void setStkBonsSortieses(Set<StkBonsSorties> stkBonsSortieses) {
        this.stkBonsSortieses = stkBonsSortieses;
    }




}


