package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComStructures;
import com.horus.ankata.core.domain.flotte.FltDdesInvsPieces;
import com.horus.ankata.core.domain.flotte.FltVehicules;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StkBonsSorties generated by hbm2java
 */
@Entity
@Table(name="stk_bons_sorties"
    ,catalog="ankata_db"
)
public class StkBonsSorties  implements java.io.Serializable {


     private Long id;
     private ComStructures comStructures;
     private FltVehicules fltVehicules;
     private StkBonsCommandesInternes stkBonsCommandesInternes;
     private StkMagasins stkMagasins;
     private Date dateBon;
     private String description;
     private Long diagnostic;
     private Integer etat;
     private String numBon;
     private Set<StkBonsSortiesLignes> stkBonsSortiesLigneses = new HashSet<StkBonsSortiesLignes>(0);
     private Set<FltDdesInvsPieces> fltDdesInvsPieceses = new HashSet<FltDdesInvsPieces>(0);

    public StkBonsSorties() {
    }

    public StkBonsSorties(ComStructures comStructures, FltVehicules fltVehicules, StkBonsCommandesInternes stkBonsCommandesInternes, StkMagasins stkMagasins, Date dateBon, String description, Long diagnostic, Integer etat, String numBon, Set<StkBonsSortiesLignes> stkBonsSortiesLigneses, Set<FltDdesInvsPieces> fltDdesInvsPieceses) {
       this.comStructures = comStructures;
       this.fltVehicules = fltVehicules;
       this.stkBonsCommandesInternes = stkBonsCommandesInternes;
       this.stkMagasins = stkMagasins;
       this.dateBon = dateBon;
       this.description = description;
       this.diagnostic = diagnostic;
       this.etat = etat;
       this.numBon = numBon;
       this.stkBonsSortiesLigneses = stkBonsSortiesLigneses;
       this.fltDdesInvsPieceses = fltDdesInvsPieceses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="structure")
    public ComStructures getComStructures() {
        return this.comStructures;
    }
    
    public void setComStructures(ComStructures comStructures) {
        this.comStructures = comStructures;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicule")
    public FltVehicules getFltVehicules() {
        return this.fltVehicules;
    }
    
    public void setFltVehicules(FltVehicules fltVehicules) {
        this.fltVehicules = fltVehicules;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bon_ci")
    public StkBonsCommandesInternes getStkBonsCommandesInternes() {
        return this.stkBonsCommandesInternes;
    }
    
    public void setStkBonsCommandesInternes(StkBonsCommandesInternes stkBonsCommandesInternes) {
        this.stkBonsCommandesInternes = stkBonsCommandesInternes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="magasin")
    public StkMagasins getStkMagasins() {
        return this.stkMagasins;
    }
    
    public void setStkMagasins(StkMagasins stkMagasins) {
        this.stkMagasins = stkMagasins;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_bon", length=10)
    public Date getDateBon() {
        return this.dateBon;
    }
    
    public void setDateBon(Date dateBon) {
        this.dateBon = dateBon;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="diagnostic")
    public Long getDiagnostic() {
        return this.diagnostic;
    }
    
    public void setDiagnostic(Long diagnostic) {
        this.diagnostic = diagnostic;
    }

    
    @Column(name="etat")
    public Integer getEtat() {
        return this.etat;
    }
    
    public void setEtat(Integer etat) {
        this.etat = etat;
    }

    
    @Column(name="num_bon", length=20)
    public String getNumBon() {
        return this.numBon;
    }
    
    public void setNumBon(String numBon) {
        this.numBon = numBon;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkBonsSorties")
    public Set<StkBonsSortiesLignes> getStkBonsSortiesLigneses() {
        return this.stkBonsSortiesLigneses;
    }
    
    public void setStkBonsSortiesLigneses(Set<StkBonsSortiesLignes> stkBonsSortiesLigneses) {
        this.stkBonsSortiesLigneses = stkBonsSortiesLigneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkBonsSorties")
    public Set<FltDdesInvsPieces> getFltDdesInvsPieceses() {
        return this.fltDdesInvsPieceses;
    }
    
    public void setFltDdesInvsPieceses(Set<FltDdesInvsPieces> fltDdesInvsPieceses) {
        this.fltDdesInvsPieceses = fltDdesInvsPieceses;
    }




}


