package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComUnites;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StkBonsSortiesLignes generated by hbm2java
 */
@Entity
@Table(name="stk_bons_sorties_lignes"
    ,catalog="ankata_db"
)
public class StkBonsSortiesLignes  implements java.io.Serializable {


     private Long id;
     private ComUnites comUnites;
     private StkArticles stkArticles;
     private StkBonsSorties stkBonsSorties;
     private String designation;
     private Double qte;

    public StkBonsSortiesLignes() {
    }

    public StkBonsSortiesLignes(ComUnites comUnites, StkArticles stkArticles, StkBonsSorties stkBonsSorties, String designation, Double qte) {
       this.comUnites = comUnites;
       this.stkArticles = stkArticles;
       this.stkBonsSorties = stkBonsSorties;
       this.designation = designation;
       this.qte = qte;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unite")
    public ComUnites getComUnites() {
        return this.comUnites;
    }
    
    public void setComUnites(ComUnites comUnites) {
        this.comUnites = comUnites;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="article")
    public StkArticles getStkArticles() {
        return this.stkArticles;
    }
    
    public void setStkArticles(StkArticles stkArticles) {
        this.stkArticles = stkArticles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bon")
    public StkBonsSorties getStkBonsSorties() {
        return this.stkBonsSorties;
    }
    
    public void setStkBonsSorties(StkBonsSorties stkBonsSorties) {
        this.stkBonsSorties = stkBonsSorties;
    }

    
    @Column(name="designation", length=300)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    
    @Column(name="qte", precision=22, scale=0)
    public Double getQte() {
        return this.qte;
    }
    
    public void setQte(Double qte) {
        this.qte = qte;
    }




}


