package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StkInventairesLignes generated by hbm2java
 */
@Entity
@Table(name="stk_inventaires_lignes"
    ,catalog="ankata_db"
)
public class StkInventairesLignes  implements java.io.Serializable {


     private Long id;
     private StkInventaires stkInventaires;
     private String code;
     private String depot;
     private String description;
     private String famille;
     private String libelleArticle;
     private Integer nbrPiece;
     private Double pump;
     private Double pumpTotal;
     private Integer qteUtil;
     private Integer quantite;
     private String unite;

    public StkInventairesLignes() {
    }

    public StkInventairesLignes(StkInventaires stkInventaires, String code, String depot, String description, String famille, String libelleArticle, Integer nbrPiece, Double pump, Double pumpTotal, Integer qteUtil, Integer quantite, String unite) {
       this.stkInventaires = stkInventaires;
       this.code = code;
       this.depot = depot;
       this.description = description;
       this.famille = famille;
       this.libelleArticle = libelleArticle;
       this.nbrPiece = nbrPiece;
       this.pump = pump;
       this.pumpTotal = pumpTotal;
       this.qteUtil = qteUtil;
       this.quantite = quantite;
       this.unite = unite;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="inventaire")
    public StkInventaires getStkInventaires() {
        return this.stkInventaires;
    }
    
    public void setStkInventaires(StkInventaires stkInventaires) {
        this.stkInventaires = stkInventaires;
    }

    
    @Column(name="code", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="depot", length=45)
    public String getDepot() {
        return this.depot;
    }
    
    public void setDepot(String depot) {
        this.depot = depot;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="famille", length=45)
    public String getFamille() {
        return this.famille;
    }
    
    public void setFamille(String famille) {
        this.famille = famille;
    }

    
    @Column(name="libelle_article", length=45)
    public String getLibelleArticle() {
        return this.libelleArticle;
    }
    
    public void setLibelleArticle(String libelleArticle) {
        this.libelleArticle = libelleArticle;
    }

    
    @Column(name="nbr_piece")
    public Integer getNbrPiece() {
        return this.nbrPiece;
    }
    
    public void setNbrPiece(Integer nbrPiece) {
        this.nbrPiece = nbrPiece;
    }

    
    @Column(name="pump", precision=22, scale=0)
    public Double getPump() {
        return this.pump;
    }
    
    public void setPump(Double pump) {
        this.pump = pump;
    }

    
    @Column(name="pump_total", precision=22, scale=0)
    public Double getPumpTotal() {
        return this.pumpTotal;
    }
    
    public void setPumpTotal(Double pumpTotal) {
        this.pumpTotal = pumpTotal;
    }

    
    @Column(name="qte_util")
    public Integer getQteUtil() {
        return this.qteUtil;
    }
    
    public void setQteUtil(Integer qteUtil) {
        this.qteUtil = qteUtil;
    }

    
    @Column(name="quantite")
    public Integer getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Integer quantite) {
        this.quantite = quantite;
    }

    
    @Column(name="unite", length=20)
    public String getUnite() {
        return this.unite;
    }
    
    public void setUnite(String unite) {
        this.unite = unite;
    }




}


