package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComFournisseurs;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StkStocksEntrees generated by hbm2java
 */
@Entity
@Table(name="stk_stocks_entrees"
    ,catalog="ankata_db"
)
public class StkStocksEntrees  implements java.io.Serializable {


     private Long id;
     private ComFournisseurs comFournisseurs;
     private StkStocks stkStocks;
     private String article;
     private Date dateEntree;
     private Double pua;
     private Double qteEntree;
     private String receptionnePar;

    public StkStocksEntrees() {
    }

    public StkStocksEntrees(ComFournisseurs comFournisseurs, StkStocks stkStocks, String article, Date dateEntree, Double pua, Double qteEntree, String receptionnePar) {
       this.comFournisseurs = comFournisseurs;
       this.stkStocks = stkStocks;
       this.article = article;
       this.dateEntree = dateEntree;
       this.pua = pua;
       this.qteEntree = qteEntree;
       this.receptionnePar = receptionnePar;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fournisseur")
    public ComFournisseurs getComFournisseurs() {
        return this.comFournisseurs;
    }
    
    public void setComFournisseurs(ComFournisseurs comFournisseurs) {
        this.comFournisseurs = comFournisseurs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stock")
    public StkStocks getStkStocks() {
        return this.stkStocks;
    }
    
    public void setStkStocks(StkStocks stkStocks) {
        this.stkStocks = stkStocks;
    }

    
    @Column(name="article")
    public String getArticle() {
        return this.article;
    }
    
    public void setArticle(String article) {
        this.article = article;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_entree", length=10)
    public Date getDateEntree() {
        return this.dateEntree;
    }
    
    public void setDateEntree(Date dateEntree) {
        this.dateEntree = dateEntree;
    }

    
    @Column(name="pua", precision=22, scale=0)
    public Double getPua() {
        return this.pua;
    }
    
    public void setPua(Double pua) {
        this.pua = pua;
    }

    
    @Column(name="qte_entree", precision=22, scale=0)
    public Double getQteEntree() {
        return this.qteEntree;
    }
    
    public void setQteEntree(Double qteEntree) {
        this.qteEntree = qteEntree;
    }

    
    @Column(name="receptionne_par", length=200)
    public String getReceptionnePar() {
        return this.receptionnePar;
    }
    
    public void setReceptionnePar(String receptionnePar) {
        this.receptionnePar = receptionnePar;
    }




}


