package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FltTrajetsDetails generated by hbm2java
 */
@Entity
@Table(name="flt_trajets_details"
    ,catalog="ankata_db"
)
public class FltTrajetsDetails  implements java.io.Serializable {


     private Long id;
     private FltModeles fltModeles;
     private FltTrajets fltTrajets;
     private Double consommation;
     private String description;
     private Double fraisroute;
     private String libelle;
     private Double prime;

    public FltTrajetsDetails() {
    }

    public FltTrajetsDetails(FltModeles fltModeles, FltTrajets fltTrajets, Double consommation, String description, Double fraisroute, String libelle, Double prime) {
       this.fltModeles = fltModeles;
       this.fltTrajets = fltTrajets;
       this.consommation = consommation;
       this.description = description;
       this.fraisroute = fraisroute;
       this.libelle = libelle;
       this.prime = prime;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="model")
    public FltModeles getFltModeles() {
        return this.fltModeles;
    }
    
    public void setFltModeles(FltModeles fltModeles) {
        this.fltModeles = fltModeles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="trajet")
    public FltTrajets getFltTrajets() {
        return this.fltTrajets;
    }
    
    public void setFltTrajets(FltTrajets fltTrajets) {
        this.fltTrajets = fltTrajets;
    }

    
    @Column(name="consommation", precision=22, scale=0)
    public Double getConsommation() {
        return this.consommation;
    }
    
    public void setConsommation(Double consommation) {
        this.consommation = consommation;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="fraisroute", precision=22, scale=0)
    public Double getFraisroute() {
        return this.fraisroute;
    }
    
    public void setFraisroute(Double fraisroute) {
        this.fraisroute = fraisroute;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="prime", precision=22, scale=0)
    public Double getPrime() {
        return this.prime;
    }
    
    public void setPrime(Double prime) {
        this.prime = prime;
    }




}


