package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.stock.StkArticlesFamillesChamps;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComNaturesChamps generated by hbm2java
 */
@Entity
@Table(name="com_natures_champs"
    ,catalog="ankata_db"
)
public class ComNaturesChamps  implements java.io.Serializable {


     private String code;
     private String libelle;
     private Set<StkArticlesFamillesChamps> stkArticlesFamillesChampses = new HashSet<StkArticlesFamillesChamps>(0);

    public ComNaturesChamps() {
    }

	
    public ComNaturesChamps(String code) {
        this.code = code;
    }
    public ComNaturesChamps(String code, String libelle, Set<StkArticlesFamillesChamps> stkArticlesFamillesChampses) {
       this.code = code;
       this.libelle = libelle;
       this.stkArticlesFamillesChampses = stkArticlesFamillesChampses;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=5)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comNaturesChamps")
    public Set<StkArticlesFamillesChamps> getStkArticlesFamillesChampses() {
        return this.stkArticlesFamillesChampses;
    }
    
    public void setStkArticlesFamillesChampses(Set<StkArticlesFamillesChamps> stkArticlesFamillesChampses) {
        this.stkArticlesFamillesChampses = stkArticlesFamillesChampses;
    }




}


