package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComLocalites;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FltTrajets generated by hbm2java
 */
@Entity
@Table(name="flt_trajets"
    ,catalog="ankata_db"
)
public class FltTrajets  implements java.io.Serializable {


     private Long id;
     private ComLocalites comLocalitesByDepart;
     private ComLocalites comLocalitesByArrive;
     private String description;
     private Double distance;
     private Double duree;
     private String libelle;
     private Set<FltMissions> fltMissionses = new HashSet<FltMissions>(0);
     private Set<FltTrajetsDetails> fltTrajetsDetailses = new HashSet<FltTrajetsDetails>(0);

    public FltTrajets() {
    }

    public FltTrajets(ComLocalites comLocalitesByDepart, ComLocalites comLocalitesByArrive, String description, Double distance, Double duree, String libelle, Set<FltMissions> fltMissionses, Set<FltTrajetsDetails> fltTrajetsDetailses) {
       this.comLocalitesByDepart = comLocalitesByDepart;
       this.comLocalitesByArrive = comLocalitesByArrive;
       this.description = description;
       this.distance = distance;
       this.duree = duree;
       this.libelle = libelle;
       this.fltMissionses = fltMissionses;
       this.fltTrajetsDetailses = fltTrajetsDetailses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="depart")
    public ComLocalites getComLocalitesByDepart() {
        return this.comLocalitesByDepart;
    }
    
    public void setComLocalitesByDepart(ComLocalites comLocalitesByDepart) {
        this.comLocalitesByDepart = comLocalitesByDepart;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="arrive")
    public ComLocalites getComLocalitesByArrive() {
        return this.comLocalitesByArrive;
    }
    
    public void setComLocalitesByArrive(ComLocalites comLocalitesByArrive) {
        this.comLocalitesByArrive = comLocalitesByArrive;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="distance", precision=22, scale=0)
    public Double getDistance() {
        return this.distance;
    }
    
    public void setDistance(Double distance) {
        this.distance = distance;
    }

    
    @Column(name="duree", precision=22, scale=0)
    public Double getDuree() {
        return this.duree;
    }
    
    public void setDuree(Double duree) {
        this.duree = duree;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltTrajets")
    public Set<FltMissions> getFltMissionses() {
        return this.fltMissionses;
    }
    
    public void setFltMissionses(Set<FltMissions> fltMissionses) {
        this.fltMissionses = fltMissionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltTrajets")
    public Set<FltTrajetsDetails> getFltTrajetsDetailses() {
        return this.fltTrajetsDetailses;
    }
    
    public void setFltTrajetsDetailses(Set<FltTrajetsDetails> fltTrajetsDetailses) {
        this.fltTrajetsDetailses = fltTrajetsDetailses;
    }




}


