package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComNaturesChamps;
import com.horus.ankata.core.domain.commons.ComTypesChamps;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * StkArticlesFamillesChamps generated by hbm2java
 */
@Entity
@Table(name="stk_articles_familles_champs"
    ,catalog="ankata_db"
)
public class StkArticlesFamillesChamps  implements java.io.Serializable {


     private Long id;
     private ComNaturesChamps comNaturesChamps;
     private ComTypesChamps comTypesChamps;
     private StkArticlesFamilles stkArticlesFamilles;
     private String code;
     private Boolean estsql;
     private Boolean etat;
     private String libelle;
     private Boolean obligatoire;
     private String valeur;
     private String valeurs;
     private Set<StkArticlesChamps> stkArticlesChampses = new HashSet<StkArticlesChamps>(0);

    public StkArticlesFamillesChamps() {
    }

    public StkArticlesFamillesChamps(ComNaturesChamps comNaturesChamps, ComTypesChamps comTypesChamps, StkArticlesFamilles stkArticlesFamilles, String code, Boolean estsql, Boolean etat, String libelle, Boolean obligatoire, String valeur, String valeurs, Set<StkArticlesChamps> stkArticlesChampses) {
       this.comNaturesChamps = comNaturesChamps;
       this.comTypesChamps = comTypesChamps;
       this.stkArticlesFamilles = stkArticlesFamilles;
       this.code = code;
       this.estsql = estsql;
       this.etat = etat;
       this.libelle = libelle;
       this.obligatoire = obligatoire;
       this.valeur = valeur;
       this.valeurs = valeurs;
       this.stkArticlesChampses = stkArticlesChampses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nature")
    public ComNaturesChamps getComNaturesChamps() {
        return this.comNaturesChamps;
    }
    
    public void setComNaturesChamps(ComNaturesChamps comNaturesChamps) {
        this.comNaturesChamps = comNaturesChamps;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_champ")
    public ComTypesChamps getComTypesChamps() {
        return this.comTypesChamps;
    }
    
    public void setComTypesChamps(ComTypesChamps comTypesChamps) {
        this.comTypesChamps = comTypesChamps;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="famille")
    public StkArticlesFamilles getStkArticlesFamilles() {
        return this.stkArticlesFamilles;
    }
    
    public void setStkArticlesFamilles(StkArticlesFamilles stkArticlesFamilles) {
        this.stkArticlesFamilles = stkArticlesFamilles;
    }

    
    @Column(name="code", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="estsql")
    public Boolean getEstsql() {
        return this.estsql;
    }
    
    public void setEstsql(Boolean estsql) {
        this.estsql = estsql;
    }

    
    @Column(name="etat")
    public Boolean getEtat() {
        return this.etat;
    }
    
    public void setEtat(Boolean etat) {
        this.etat = etat;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="obligatoire")
    public Boolean getObligatoire() {
        return this.obligatoire;
    }
    
    public void setObligatoire(Boolean obligatoire) {
        this.obligatoire = obligatoire;
    }

    
    @Column(name="valeur", length=20)
    public String getValeur() {
        return this.valeur;
    }
    
    public void setValeur(String valeur) {
        this.valeur = valeur;
    }

    
    @Column(name="valeurs")
    public String getValeurs() {
        return this.valeurs;
    }
    
    public void setValeurs(String valeurs) {
        this.valeurs = valeurs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkArticlesFamillesChamps")
    public Set<StkArticlesChamps> getStkArticlesChampses() {
        return this.stkArticlesChampses;
    }
    
    public void setStkArticlesChampses(Set<StkArticlesChamps> stkArticlesChampses) {
        this.stkArticlesChampses = stkArticlesChampses;
    }




}


