package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.vente.VteBonsLivraisons;
import com.horus.ankata.core.domain.vente.VteFacturesLignes;
import com.horus.ankata.core.domain.commons.ComClients;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FltMissions generated by hbm2java
 */
@Entity
@Table(name="flt_missions"
    ,catalog="ankata_db"
)
public class FltMissions  implements java.io.Serializable {


     private Long id;
     private ComClients comClients;
     private FltActivites fltActivites;
     private FltRemorques fltRemorques;
     private FltTrajets fltTrajets;
     private FltVehicules fltVehicules;
     private String conducteur;
     private Date dateCloture;
     private Date dateDeb;
     private Date dateDebCharg;
     private Date dateDebDecharg;
     private Date dateFinCharg;
     private Date dateFinDecharg;
     private Date datePrevueFin;
     private Date dateReelFin;
     private Date dateUtilsa;
     private String etat;
     private Double kiloDepart;
     private Double kiloRetour;
     private String nature;
     private Double nivCarbDep;
     private Double nivCarbRet;
     private String numOrdre;
     private String refAller;
     private String remisBord;
     private String travaux;
     private String typeTrajet;
     private Set<FltMissionsCharges> fltMissionsChargeses = new HashSet<FltMissionsCharges>(0);
     private Set<FltMissionsConducteurs> fltMissionsConducteurses = new HashSet<FltMissionsConducteurs>(0);
     private Set<FltMissionsEntretiens> fltMissionsEntretienses = new HashSet<FltMissionsEntretiens>(0);
     private Set<VteBonsLivraisons> vteBonsLivraisonses = new HashSet<VteBonsLivraisons>(0);
     private Set<FltMissionsSinistres> fltMissionsSinistreses = new HashSet<FltMissionsSinistres>(0);
     private Set<VteFacturesLignes> vteFacturesLigneses = new HashSet<VteFacturesLignes>(0);
     private Set<FltMissionsCarburants> fltMissionsCarburantses = new HashSet<FltMissionsCarburants>(0);
     private Set<FltMissionsInfractions> fltMissionsInfractionses = new HashSet<FltMissionsInfractions>(0);

    public FltMissions() {
    }

    public FltMissions(ComClients comClients, FltActivites fltActivites, FltRemorques fltRemorques, FltTrajets fltTrajets, FltVehicules fltVehicules, String conducteur, Date dateCloture, Date dateDeb, Date dateDebCharg, Date dateDebDecharg, Date dateFinCharg, Date dateFinDecharg, Date datePrevueFin, Date dateReelFin, Date dateUtilsa, String etat, Double kiloDepart, Double kiloRetour, String nature, Double nivCarbDep, Double nivCarbRet, String numOrdre, String refAller, String remisBord, String travaux, String typeTrajet, Set<FltMissionsCharges> fltMissionsChargeses, Set<FltMissionsConducteurs> fltMissionsConducteurses, Set<FltMissionsEntretiens> fltMissionsEntretienses, Set<VteBonsLivraisons> vteBonsLivraisonses, Set<FltMissionsSinistres> fltMissionsSinistreses, Set<VteFacturesLignes> vteFacturesLigneses, Set<FltMissionsCarburants> fltMissionsCarburantses, Set<FltMissionsInfractions> fltMissionsInfractionses) {
       this.comClients = comClients;
       this.fltActivites = fltActivites;
       this.fltRemorques = fltRemorques;
       this.fltTrajets = fltTrajets;
       this.fltVehicules = fltVehicules;
       this.conducteur = conducteur;
       this.dateCloture = dateCloture;
       this.dateDeb = dateDeb;
       this.dateDebCharg = dateDebCharg;
       this.dateDebDecharg = dateDebDecharg;
       this.dateFinCharg = dateFinCharg;
       this.dateFinDecharg = dateFinDecharg;
       this.datePrevueFin = datePrevueFin;
       this.dateReelFin = dateReelFin;
       this.dateUtilsa = dateUtilsa;
       this.etat = etat;
       this.kiloDepart = kiloDepart;
       this.kiloRetour = kiloRetour;
       this.nature = nature;
       this.nivCarbDep = nivCarbDep;
       this.nivCarbRet = nivCarbRet;
       this.numOrdre = numOrdre;
       this.refAller = refAller;
       this.remisBord = remisBord;
       this.travaux = travaux;
       this.typeTrajet = typeTrajet;
       this.fltMissionsChargeses = fltMissionsChargeses;
       this.fltMissionsConducteurses = fltMissionsConducteurses;
       this.fltMissionsEntretienses = fltMissionsEntretienses;
       this.vteBonsLivraisonses = vteBonsLivraisonses;
       this.fltMissionsSinistreses = fltMissionsSinistreses;
       this.vteFacturesLigneses = vteFacturesLigneses;
       this.fltMissionsCarburantses = fltMissionsCarburantses;
       this.fltMissionsInfractionses = fltMissionsInfractionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="client")
    public ComClients getComClients() {
        return this.comClients;
    }
    
    public void setComClients(ComClients comClients) {
        this.comClients = comClients;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="activite")
    public FltActivites getFltActivites() {
        return this.fltActivites;
    }
    
    public void setFltActivites(FltActivites fltActivites) {
        this.fltActivites = fltActivites;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="remorque")
    public FltRemorques getFltRemorques() {
        return this.fltRemorques;
    }
    
    public void setFltRemorques(FltRemorques fltRemorques) {
        this.fltRemorques = fltRemorques;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="trajet")
    public FltTrajets getFltTrajets() {
        return this.fltTrajets;
    }
    
    public void setFltTrajets(FltTrajets fltTrajets) {
        this.fltTrajets = fltTrajets;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicule")
    public FltVehicules getFltVehicules() {
        return this.fltVehicules;
    }
    
    public void setFltVehicules(FltVehicules fltVehicules) {
        this.fltVehicules = fltVehicules;
    }

    
    @Column(name="conducteur", length=200)
    public String getConducteur() {
        return this.conducteur;
    }
    
    public void setConducteur(String conducteur) {
        this.conducteur = conducteur;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_cloture", length=10)
    public Date getDateCloture() {
        return this.dateCloture;
    }
    
    public void setDateCloture(Date dateCloture) {
        this.dateCloture = dateCloture;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_deb", length=19)
    public Date getDateDeb() {
        return this.dateDeb;
    }
    
    public void setDateDeb(Date dateDeb) {
        this.dateDeb = dateDeb;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_deb_charg", length=19)
    public Date getDateDebCharg() {
        return this.dateDebCharg;
    }
    
    public void setDateDebCharg(Date dateDebCharg) {
        this.dateDebCharg = dateDebCharg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_deb_decharg", length=19)
    public Date getDateDebDecharg() {
        return this.dateDebDecharg;
    }
    
    public void setDateDebDecharg(Date dateDebDecharg) {
        this.dateDebDecharg = dateDebDecharg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_fin_charg", length=19)
    public Date getDateFinCharg() {
        return this.dateFinCharg;
    }
    
    public void setDateFinCharg(Date dateFinCharg) {
        this.dateFinCharg = dateFinCharg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_fin_decharg", length=19)
    public Date getDateFinDecharg() {
        return this.dateFinDecharg;
    }
    
    public void setDateFinDecharg(Date dateFinDecharg) {
        this.dateFinDecharg = dateFinDecharg;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_prevue_fin", length=19)
    public Date getDatePrevueFin() {
        return this.datePrevueFin;
    }
    
    public void setDatePrevueFin(Date datePrevueFin) {
        this.datePrevueFin = datePrevueFin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_reel_fin", length=19)
    public Date getDateReelFin() {
        return this.dateReelFin;
    }
    
    public void setDateReelFin(Date dateReelFin) {
        this.dateReelFin = dateReelFin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_utilsa", length=10)
    public Date getDateUtilsa() {
        return this.dateUtilsa;
    }
    
    public void setDateUtilsa(Date dateUtilsa) {
        this.dateUtilsa = dateUtilsa;
    }

    
    @Column(name="etat", length=2)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }

    
    @Column(name="kilo_depart", precision=22, scale=0)
    public Double getKiloDepart() {
        return this.kiloDepart;
    }
    
    public void setKiloDepart(Double kiloDepart) {
        this.kiloDepart = kiloDepart;
    }

    
    @Column(name="kilo_retour", precision=22, scale=0)
    public Double getKiloRetour() {
        return this.kiloRetour;
    }
    
    public void setKiloRetour(Double kiloRetour) {
        this.kiloRetour = kiloRetour;
    }

    
    @Column(name="nature", length=1)
    public String getNature() {
        return this.nature;
    }
    
    public void setNature(String nature) {
        this.nature = nature;
    }

    
    @Column(name="niv_carb_dep", precision=22, scale=0)
    public Double getNivCarbDep() {
        return this.nivCarbDep;
    }
    
    public void setNivCarbDep(Double nivCarbDep) {
        this.nivCarbDep = nivCarbDep;
    }

    
    @Column(name="niv_carb_ret", precision=22, scale=0)
    public Double getNivCarbRet() {
        return this.nivCarbRet;
    }
    
    public void setNivCarbRet(Double nivCarbRet) {
        this.nivCarbRet = nivCarbRet;
    }

    
    @Column(name="num_ordre", length=20)
    public String getNumOrdre() {
        return this.numOrdre;
    }
    
    public void setNumOrdre(String numOrdre) {
        this.numOrdre = numOrdre;
    }

    
    @Column(name="ref_aller", length=45)
    public String getRefAller() {
        return this.refAller;
    }
    
    public void setRefAller(String refAller) {
        this.refAller = refAller;
    }

    
    @Column(name="remis_bord", length=200)
    public String getRemisBord() {
        return this.remisBord;
    }
    
    public void setRemisBord(String remisBord) {
        this.remisBord = remisBord;
    }

    
    @Column(name="travaux")
    public String getTravaux() {
        return this.travaux;
    }
    
    public void setTravaux(String travaux) {
        this.travaux = travaux;
    }

    
    @Column(name="type_trajet", length=2)
    public String getTypeTrajet() {
        return this.typeTrajet;
    }
    
    public void setTypeTrajet(String typeTrajet) {
        this.typeTrajet = typeTrajet;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltMissions")
    public Set<FltMissionsCharges> getFltMissionsChargeses() {
        return this.fltMissionsChargeses;
    }
    
    public void setFltMissionsChargeses(Set<FltMissionsCharges> fltMissionsChargeses) {
        this.fltMissionsChargeses = fltMissionsChargeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltMissions")
    public Set<FltMissionsConducteurs> getFltMissionsConducteurses() {
        return this.fltMissionsConducteurses;
    }
    
    public void setFltMissionsConducteurses(Set<FltMissionsConducteurs> fltMissionsConducteurses) {
        this.fltMissionsConducteurses = fltMissionsConducteurses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltMissions")
    public Set<FltMissionsEntretiens> getFltMissionsEntretienses() {
        return this.fltMissionsEntretienses;
    }
    
    public void setFltMissionsEntretienses(Set<FltMissionsEntretiens> fltMissionsEntretienses) {
        this.fltMissionsEntretienses = fltMissionsEntretienses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltMissions")
    public Set<VteBonsLivraisons> getVteBonsLivraisonses() {
        return this.vteBonsLivraisonses;
    }
    
    public void setVteBonsLivraisonses(Set<VteBonsLivraisons> vteBonsLivraisonses) {
        this.vteBonsLivraisonses = vteBonsLivraisonses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltMissions")
    public Set<FltMissionsSinistres> getFltMissionsSinistreses() {
        return this.fltMissionsSinistreses;
    }
    
    public void setFltMissionsSinistreses(Set<FltMissionsSinistres> fltMissionsSinistreses) {
        this.fltMissionsSinistreses = fltMissionsSinistreses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltMissions")
    public Set<VteFacturesLignes> getVteFacturesLigneses() {
        return this.vteFacturesLigneses;
    }
    
    public void setVteFacturesLigneses(Set<VteFacturesLignes> vteFacturesLigneses) {
        this.vteFacturesLigneses = vteFacturesLigneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltMissions")
    public Set<FltMissionsCarburants> getFltMissionsCarburantses() {
        return this.fltMissionsCarburantses;
    }
    
    public void setFltMissionsCarburantses(Set<FltMissionsCarburants> fltMissionsCarburantses) {
        this.fltMissionsCarburantses = fltMissionsCarburantses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltMissions")
    public Set<FltMissionsInfractions> getFltMissionsInfractionses() {
        return this.fltMissionsInfractionses;
    }
    
    public void setFltMissionsInfractionses(Set<FltMissionsInfractions> fltMissionsInfractionses) {
        this.fltMissionsInfractionses = fltMissionsInfractionses;
    }




}


