package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FltAcquisitions generated by hbm2java
 */
@Entity
@Table(name="flt_acquisitions"
    ,catalog="ankata_db"
)
public class FltAcquisitions  implements java.io.Serializable {


     private Long id;
     private String code;
     private String libelle;
     private Set<FltVehicules> fltVehiculeses = new HashSet<FltVehicules>(0);
     private Set<FltRemorques> fltRemorqueses = new HashSet<FltRemorques>(0);

    public FltAcquisitions() {
    }

    public FltAcquisitions(String code, String libelle, Set<FltVehicules> fltVehiculeses, Set<FltRemorques> fltRemorqueses) {
       this.code = code;
       this.libelle = libelle;
       this.fltVehiculeses = fltVehiculeses;
       this.fltRemorqueses = fltRemorqueses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="code", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle")
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltAcquisitions")
    public Set<FltVehicules> getFltVehiculeses() {
        return this.fltVehiculeses;
    }
    
    public void setFltVehiculeses(Set<FltVehicules> fltVehiculeses) {
        this.fltVehiculeses = fltVehiculeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltAcquisitions")
    public Set<FltRemorques> getFltRemorqueses() {
        return this.fltRemorqueses;
    }
    
    public void setFltRemorqueses(Set<FltRemorques> fltRemorqueses) {
        this.fltRemorqueses = fltRemorqueses;
    }




}


