package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComEmails generated by hbm2java
 */
@Entity
@Table(name="com_emails"
    ,catalog="ankata_db"
)
public class ComEmails  implements java.io.Serializable {


     private Long id;
     private Date dateEnvoi;
     private String de;
     private String errdesc;
     private String etat;
     private String fattach;
     private String fname;
     private String message;
     private String ref;
     private String sources;
     private String subject;
     private String tocc;
     private String tocci;
     private String tod;

    public ComEmails() {
    }

    public ComEmails(Date dateEnvoi, String de, String errdesc, String etat, String fattach, String fname, String message, String ref, String sources, String subject, String tocc, String tocci, String tod) {
       this.dateEnvoi = dateEnvoi;
       this.de = de;
       this.errdesc = errdesc;
       this.etat = etat;
       this.fattach = fattach;
       this.fname = fname;
       this.message = message;
       this.ref = ref;
       this.sources = sources;
       this.subject = subject;
       this.tocc = tocc;
       this.tocci = tocci;
       this.tod = tod;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_envoi", length=10)
    public Date getDateEnvoi() {
        return this.dateEnvoi;
    }
    
    public void setDateEnvoi(Date dateEnvoi) {
        this.dateEnvoi = dateEnvoi;
    }

    
    @Column(name="de", length=200)
    public String getDe() {
        return this.de;
    }
    
    public void setDe(String de) {
        this.de = de;
    }

    
    @Column(name="errdesc")
    public String getErrdesc() {
        return this.errdesc;
    }
    
    public void setErrdesc(String errdesc) {
        this.errdesc = errdesc;
    }

    
    @Column(name="etat", length=20)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }

    
    @Column(name="fattach")
    public String getFattach() {
        return this.fattach;
    }
    
    public void setFattach(String fattach) {
        this.fattach = fattach;
    }

    
    @Column(name="fname", length=50)
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }

    
    @Column(name="message")
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="ref", length=20)
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }

    
    @Column(name="sources", length=2)
    public String getSources() {
        return this.sources;
    }
    
    public void setSources(String sources) {
        this.sources = sources;
    }

    
    @Column(name="subject")
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="tocc")
    public String getTocc() {
        return this.tocc;
    }
    
    public void setTocc(String tocc) {
        this.tocc = tocc;
    }

    
    @Column(name="tocci")
    public String getTocci() {
        return this.tocci;
    }
    
    public void setTocci(String tocci) {
        this.tocci = tocci;
    }

    
    @Column(name="tod")
    public String getTod() {
        return this.tod;
    }
    
    public void setTod(String tod) {
        this.tod = tod;
    }




}


