package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComStructures;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FltParcs generated by hbm2java
 */
@Entity
@Table(name="flt_parcs"
    ,catalog="ankata_db"
)
public class FltParcs  implements java.io.Serializable {


     private Long id;
     private ComStructures comStructures;
     private FltParcs fltParcs;
     private String code;
     private String libelle;
     private String statut;
     private Set<FltParcs> fltParcses = new HashSet<FltParcs>(0);
     private Set<FltRemorques> fltRemorqueses = new HashSet<FltRemorques>(0);
     private Set<FltVehicules> fltVehiculeses = new HashSet<FltVehicules>(0);

    public FltParcs() {
    }

    public FltParcs(ComStructures comStructures, FltParcs fltParcs, String code, String libelle, String statut, Set<FltParcs> fltParcses, Set<FltRemorques> fltRemorqueses, Set<FltVehicules> fltVehiculeses) {
       this.comStructures = comStructures;
       this.fltParcs = fltParcs;
       this.code = code;
       this.libelle = libelle;
       this.statut = statut;
       this.fltParcses = fltParcses;
       this.fltRemorqueses = fltRemorqueses;
       this.fltVehiculeses = fltVehiculeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="structure")
    public ComStructures getComStructures() {
        return this.comStructures;
    }
    
    public void setComStructures(ComStructures comStructures) {
        this.comStructures = comStructures;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent")
    public FltParcs getFltParcs() {
        return this.fltParcs;
    }
    
    public void setFltParcs(FltParcs fltParcs) {
        this.fltParcs = fltParcs;
    }

    
    @Column(name="code", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=250)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="statut", length=2)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltParcs")
    public Set<FltParcs> getFltParcses() {
        return this.fltParcses;
    }
    
    public void setFltParcses(Set<FltParcs> fltParcses) {
        this.fltParcses = fltParcses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltParcs")
    public Set<FltRemorques> getFltRemorqueses() {
        return this.fltRemorqueses;
    }
    
    public void setFltRemorqueses(Set<FltRemorques> fltRemorqueses) {
        this.fltRemorqueses = fltRemorqueses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltParcs")
    public Set<FltVehicules> getFltVehiculeses() {
        return this.fltVehiculeses;
    }
    
    public void setFltVehiculeses(Set<FltVehicules> fltVehiculeses) {
        this.fltVehiculeses = fltVehiculeses;
    }




}


