package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FltDdesInvs generated by hbm2java
 */
@Entity
@Table(name="flt_ddes_invs"
    ,catalog="ankata_db"
)
public class FltDdesInvs  implements java.io.Serializable {


     private Long id;
     private FltDdesInvsGravites fltDdesInvsGravites;
     private FltDdesInvsLieux fltDdesInvsLieux;
     private FltDdesInvsNatures fltDdesInvsNatures;
     private FltDdesInvsPriorites fltDdesInvsPriorites;
     private FltDdesInvsTypes fltDdesInvsTypes;
     private FltVehicules fltVehicules;
     private Date dateDde;
     private Date dateDebut;
     private Date dateFin;
     private Date datePrevue;
     private String description;
     private Integer etat;
     private Integer km;
     private Double mtMoHt;
     private Double mtPieceHt;
     private Double mtTotalHt;
     private Set<FltDdesInvsPieces> fltDdesInvsPieceses = new HashSet<FltDdesInvsPieces>(0);
     private Set<FltDdesInvsPers> fltDdesInvsPerses = new HashSet<FltDdesInvsPers>(0);

    public FltDdesInvs() {
    }

	
    public FltDdesInvs(Date dateDebut) {
        this.dateDebut = dateDebut;
    }
    public FltDdesInvs(FltDdesInvsGravites fltDdesInvsGravites, FltDdesInvsLieux fltDdesInvsLieux, FltDdesInvsNatures fltDdesInvsNatures, FltDdesInvsPriorites fltDdesInvsPriorites, FltDdesInvsTypes fltDdesInvsTypes, FltVehicules fltVehicules, Date dateDde, Date dateDebut, Date dateFin, Date datePrevue, String description, Integer etat, Integer km, Double mtMoHt, Double mtPieceHt, Double mtTotalHt, Set<FltDdesInvsPieces> fltDdesInvsPieceses, Set<FltDdesInvsPers> fltDdesInvsPerses) {
       this.fltDdesInvsGravites = fltDdesInvsGravites;
       this.fltDdesInvsLieux = fltDdesInvsLieux;
       this.fltDdesInvsNatures = fltDdesInvsNatures;
       this.fltDdesInvsPriorites = fltDdesInvsPriorites;
       this.fltDdesInvsTypes = fltDdesInvsTypes;
       this.fltVehicules = fltVehicules;
       this.dateDde = dateDde;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.datePrevue = datePrevue;
       this.description = description;
       this.etat = etat;
       this.km = km;
       this.mtMoHt = mtMoHt;
       this.mtPieceHt = mtPieceHt;
       this.mtTotalHt = mtTotalHt;
       this.fltDdesInvsPieceses = fltDdesInvsPieceses;
       this.fltDdesInvsPerses = fltDdesInvsPerses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grative")
    public FltDdesInvsGravites getFltDdesInvsGravites() {
        return this.fltDdesInvsGravites;
    }
    
    public void setFltDdesInvsGravites(FltDdesInvsGravites fltDdesInvsGravites) {
        this.fltDdesInvsGravites = fltDdesInvsGravites;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="lieu")
    public FltDdesInvsLieux getFltDdesInvsLieux() {
        return this.fltDdesInvsLieux;
    }
    
    public void setFltDdesInvsLieux(FltDdesInvsLieux fltDdesInvsLieux) {
        this.fltDdesInvsLieux = fltDdesInvsLieux;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nature")
    public FltDdesInvsNatures getFltDdesInvsNatures() {
        return this.fltDdesInvsNatures;
    }
    
    public void setFltDdesInvsNatures(FltDdesInvsNatures fltDdesInvsNatures) {
        this.fltDdesInvsNatures = fltDdesInvsNatures;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="priorite")
    public FltDdesInvsPriorites getFltDdesInvsPriorites() {
        return this.fltDdesInvsPriorites;
    }
    
    public void setFltDdesInvsPriorites(FltDdesInvsPriorites fltDdesInvsPriorites) {
        this.fltDdesInvsPriorites = fltDdesInvsPriorites;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_dde")
    public FltDdesInvsTypes getFltDdesInvsTypes() {
        return this.fltDdesInvsTypes;
    }
    
    public void setFltDdesInvsTypes(FltDdesInvsTypes fltDdesInvsTypes) {
        this.fltDdesInvsTypes = fltDdesInvsTypes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicule")
    public FltVehicules getFltVehicules() {
        return this.fltVehicules;
    }
    
    public void setFltVehicules(FltVehicules fltVehicules) {
        this.fltVehicules = fltVehicules;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_dde", length=10)
    public Date getDateDde() {
        return this.dateDde;
    }
    
    public void setDateDde(Date dateDde) {
        this.dateDde = dateDde;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_debut", nullable=false, length=19)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_fin", length=10)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_prevue", length=10)
    public Date getDatePrevue() {
        return this.datePrevue;
    }
    
    public void setDatePrevue(Date datePrevue) {
        this.datePrevue = datePrevue;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="etat")
    public Integer getEtat() {
        return this.etat;
    }
    
    public void setEtat(Integer etat) {
        this.etat = etat;
    }

    
    @Column(name="km")
    public Integer getKm() {
        return this.km;
    }
    
    public void setKm(Integer km) {
        this.km = km;
    }

    
    @Column(name="mt_mo_ht", precision=22, scale=0)
    public Double getMtMoHt() {
        return this.mtMoHt;
    }
    
    public void setMtMoHt(Double mtMoHt) {
        this.mtMoHt = mtMoHt;
    }

    
    @Column(name="mt_piece_ht", precision=22, scale=0)
    public Double getMtPieceHt() {
        return this.mtPieceHt;
    }
    
    public void setMtPieceHt(Double mtPieceHt) {
        this.mtPieceHt = mtPieceHt;
    }

    
    @Column(name="mt_total_ht", precision=22, scale=0)
    public Double getMtTotalHt() {
        return this.mtTotalHt;
    }
    
    public void setMtTotalHt(Double mtTotalHt) {
        this.mtTotalHt = mtTotalHt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltDdesInvs")
    public Set<FltDdesInvsPieces> getFltDdesInvsPieceses() {
        return this.fltDdesInvsPieceses;
    }
    
    public void setFltDdesInvsPieceses(Set<FltDdesInvsPieces> fltDdesInvsPieceses) {
        this.fltDdesInvsPieceses = fltDdesInvsPieceses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltDdesInvs")
    public Set<FltDdesInvsPers> getFltDdesInvsPerses() {
        return this.fltDdesInvsPerses;
    }
    
    public void setFltDdesInvsPerses(Set<FltDdesInvsPers> fltDdesInvsPerses) {
        this.fltDdesInvsPerses = fltDdesInvsPerses;
    }




}


