package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.achat.AchBonsDecaissements;
import com.horus.ankata.core.domain.vente.VteBonsEncaissements;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * ComCaisses generated by hbm2java
 */
@Entity
@Table(name="com_caisses"
    ,catalog="ankata_db"
    , uniqueConstraints = @UniqueConstraint(columnNames="code") 
)
public class ComCaisses  implements java.io.Serializable {


     private Long id;
     private String code;
     private String libelle;
     private Set<AchBonsDecaissements> achBonsDecaissementses = new HashSet<AchBonsDecaissements>(0);
     private Set<VteBonsEncaissements> vteBonsEncaissementses = new HashSet<VteBonsEncaissements>(0);

    public ComCaisses() {
    }

    public ComCaisses(String code, String libelle, Set<AchBonsDecaissements> achBonsDecaissementses, Set<VteBonsEncaissements> vteBonsEncaissementses) {
       this.code = code;
       this.libelle = libelle;
       this.achBonsDecaissementses = achBonsDecaissementses;
       this.vteBonsEncaissementses = vteBonsEncaissementses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="code", unique=true, length=45)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comCaisses")
    public Set<AchBonsDecaissements> getAchBonsDecaissementses() {
        return this.achBonsDecaissementses;
    }
    
    public void setAchBonsDecaissementses(Set<AchBonsDecaissements> achBonsDecaissementses) {
        this.achBonsDecaissementses = achBonsDecaissementses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comCaisses")
    public Set<VteBonsEncaissements> getVteBonsEncaissementses() {
        return this.vteBonsEncaissementses;
    }
    
    public void setVteBonsEncaissementses(Set<VteBonsEncaissements> vteBonsEncaissementses) {
        this.vteBonsEncaissementses = vteBonsEncaissementses;
    }




}


