package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.flotte.FltMissions;
import com.horus.ankata.core.domain.flotte.FltReservation;
import com.horus.ankata.core.domain.stock.StkStocksSorties;
import com.horus.ankata.core.domain.vente.VteDevis;
import com.horus.ankata.core.domain.vente.VteFactures;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComClients generated by hbm2java
 */
@Entity
@Table(name="com_clients"
    ,catalog="ankata_db"
)
public class ComClients  implements java.io.Serializable {


     private Long id;
     private ComPersonnes comPersonnes;
     private Set<VteDevis> vteDevises = new HashSet<VteDevis>(0);
     private Set<VteFactures> vteFactureses = new HashSet<VteFactures>(0);
     private Set<FltReservation> fltReservations = new HashSet<FltReservation>(0);
     private Set<StkStocksSorties> stkStocksSortieses = new HashSet<StkStocksSorties>(0);
     private Set<FltMissions> fltMissionses = new HashSet<FltMissions>(0);

    public ComClients() {
    }

    public ComClients(ComPersonnes comPersonnes, Set<VteDevis> vteDevises, Set<VteFactures> vteFactureses, Set<FltReservation> fltReservations, Set<StkStocksSorties> stkStocksSortieses, Set<FltMissions> fltMissionses) {
       this.comPersonnes = comPersonnes;
       this.vteDevises = vteDevises;
       this.vteFactureses = vteFactureses;
       this.fltReservations = fltReservations;
       this.stkStocksSortieses = stkStocksSortieses;
       this.fltMissionses = fltMissionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="personne")
    public ComPersonnes getComPersonnes() {
        return this.comPersonnes;
    }
    
    public void setComPersonnes(ComPersonnes comPersonnes) {
        this.comPersonnes = comPersonnes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comClients")
    public Set<VteDevis> getVteDevises() {
        return this.vteDevises;
    }
    
    public void setVteDevises(Set<VteDevis> vteDevises) {
        this.vteDevises = vteDevises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comClients")
    public Set<VteFactures> getVteFactureses() {
        return this.vteFactureses;
    }
    
    public void setVteFactureses(Set<VteFactures> vteFactureses) {
        this.vteFactureses = vteFactureses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comClients")
    public Set<FltReservation> getFltReservations() {
        return this.fltReservations;
    }
    
    public void setFltReservations(Set<FltReservation> fltReservations) {
        this.fltReservations = fltReservations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comClients")
    public Set<StkStocksSorties> getStkStocksSortieses() {
        return this.stkStocksSortieses;
    }
    
    public void setStkStocksSortieses(Set<StkStocksSorties> stkStocksSortieses) {
        this.stkStocksSortieses = stkStocksSortieses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comClients")
    public Set<FltMissions> getFltMissionses() {
        return this.fltMissionses;
    }
    
    public void setFltMissionses(Set<FltMissions> fltMissionses) {
        this.fltMissionses = fltMissionses;
    }




}


