package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComFonctions generated by hbm2java
 */
@Entity
@Table(name="com_fonctions"
    ,catalog="ankata_db"
)
public class ComFonctions  implements java.io.Serializable {


     private Long id;
     private String libelle;
     private Set<ComPersonnes> comPersonneses = new HashSet<ComPersonnes>(0);

    public ComFonctions() {
    }

    public ComFonctions(String libelle, Set<ComPersonnes> comPersonneses) {
       this.libelle = libelle;
       this.comPersonneses = comPersonneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comFonctions")
    public Set<ComPersonnes> getComPersonneses() {
        return this.comPersonneses;
    }
    
    public void setComPersonneses(Set<ComPersonnes> comPersonneses) {
        this.comPersonneses = comPersonneses;
    }




}


