package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.achat.*;
import com.horus.ankata.core.domain.flotte.FltMissionsCarburants;
import com.horus.ankata.core.domain.flotte.FltMissionsCharges;
import com.horus.ankata.core.domain.flotte.FltMissionsEntretiens;
import com.horus.ankata.core.domain.stock.StkStocksEntrees;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComFournisseurs generated by hbm2java
 */
@Entity
@Table(name="com_fournisseurs"
    ,catalog="ankata_db"
)
public class ComFournisseurs  implements java.io.Serializable {


     private Long id;
     private ComPersonnes comPersonnes;
     private Set<AchBonsLivraisons> achBonsLivraisonses = new HashSet<AchBonsLivraisons>(0);
     private Set<AchDevis> achDevises = new HashSet<AchDevis>(0);
     private Set<StkStocksEntrees> stkStocksEntreeses = new HashSet<StkStocksEntrees>(0);
     private Set<FltMissionsCarburants> fltMissionsCarburantses = new HashSet<FltMissionsCarburants>(0);
     private Set<FltMissionsEntretiens> fltMissionsEntretienses = new HashSet<FltMissionsEntretiens>(0);
     private Set<AchFactures> achFactureses = new HashSet<AchFactures>(0);
     private Set<FltMissionsCharges> fltMissionsChargeses = new HashSet<FltMissionsCharges>(0);
     private Set<AchBonsCommandes> achBonsCommandeses = new HashSet<AchBonsCommandes>(0);

    public ComFournisseurs() {
    }

    public ComFournisseurs(ComPersonnes comPersonnes, Set<AchBonsLivraisons> achBonsLivraisonses, Set<AchDevis> achDevises, Set<StkStocksEntrees> stkStocksEntreeses, Set<FltMissionsCarburants> fltMissionsCarburantses, Set<FltMissionsEntretiens> fltMissionsEntretienses, Set<AchFactures> achFactureses, Set<FltMissionsCharges> fltMissionsChargeses, Set<AchBonsCommandes> achBonsCommandeses) {
       this.comPersonnes = comPersonnes;
       this.achBonsLivraisonses = achBonsLivraisonses;
       this.achDevises = achDevises;
       this.stkStocksEntreeses = stkStocksEntreeses;
       this.fltMissionsCarburantses = fltMissionsCarburantses;
       this.fltMissionsEntretienses = fltMissionsEntretienses;
       this.achFactureses = achFactureses;
       this.fltMissionsChargeses = fltMissionsChargeses;
       this.achBonsCommandeses = achBonsCommandeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="personne")
    public ComPersonnes getComPersonnes() {
        return this.comPersonnes;
    }
    
    public void setComPersonnes(ComPersonnes comPersonnes) {
        this.comPersonnes = comPersonnes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comFournisseurs")
    public Set<AchBonsLivraisons> getAchBonsLivraisonses() {
        return this.achBonsLivraisonses;
    }
    
    public void setAchBonsLivraisonses(Set<AchBonsLivraisons> achBonsLivraisonses) {
        this.achBonsLivraisonses = achBonsLivraisonses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comFournisseurs")
    public Set<AchDevis> getAchDevises() {
        return this.achDevises;
    }
    
    public void setAchDevises(Set<AchDevis> achDevises) {
        this.achDevises = achDevises;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comFournisseurs")
    public Set<StkStocksEntrees> getStkStocksEntreeses() {
        return this.stkStocksEntreeses;
    }
    
    public void setStkStocksEntreeses(Set<StkStocksEntrees> stkStocksEntreeses) {
        this.stkStocksEntreeses = stkStocksEntreeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comFournisseurs")
    public Set<FltMissionsCarburants> getFltMissionsCarburantses() {
        return this.fltMissionsCarburantses;
    }
    
    public void setFltMissionsCarburantses(Set<FltMissionsCarburants> fltMissionsCarburantses) {
        this.fltMissionsCarburantses = fltMissionsCarburantses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comFournisseurs")
    public Set<FltMissionsEntretiens> getFltMissionsEntretienses() {
        return this.fltMissionsEntretienses;
    }
    
    public void setFltMissionsEntretienses(Set<FltMissionsEntretiens> fltMissionsEntretienses) {
        this.fltMissionsEntretienses = fltMissionsEntretienses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comFournisseurs")
    public Set<AchFactures> getAchFactureses() {
        return this.achFactureses;
    }
    
    public void setAchFactureses(Set<AchFactures> achFactureses) {
        this.achFactureses = achFactureses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comFournisseurs")
    public Set<FltMissionsCharges> getFltMissionsChargeses() {
        return this.fltMissionsChargeses;
    }
    
    public void setFltMissionsChargeses(Set<FltMissionsCharges> fltMissionsChargeses) {
        this.fltMissionsChargeses = fltMissionsChargeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comFournisseurs")
    public Set<AchBonsCommandes> getAchBonsCommandeses() {
        return this.achBonsCommandeses;
    }
    
    public void setAchBonsCommandeses(Set<AchBonsCommandes> achBonsCommandeses) {
        this.achBonsCommandeses = achBonsCommandeses;
    }




}


