package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComMenus generated by hbm2java
 */
@Entity
@Table(name="com_menus"
    ,catalog="ankata_db"
)
public class ComMenus  implements java.io.Serializable {


     private String code;
     private ComMenus comMenus;
     private String enable;
     private String icon;
     private String libelle;
     private String msgkey;
     private Integer ordre;
     private String page;
     private Boolean selected;
     private String type;
     private Set<ComRoles> comRoleses = new HashSet<ComRoles>(0);
     private Set<ComMenus> comMenuses = new HashSet<ComMenus>(0);

    public ComMenus() {
    }

	
    public ComMenus(String code) {
        this.code = code;
    }
    public ComMenus(String code, ComMenus comMenus, String enable, String icon, String libelle, String msgkey, Integer ordre, String page, Boolean selected, String type, Set<ComRoles> comRoleses, Set<ComMenus> comMenuses) {
       this.code = code;
       this.comMenus = comMenus;
       this.enable = enable;
       this.icon = icon;
       this.libelle = libelle;
       this.msgkey = msgkey;
       this.ordre = ordre;
       this.page = page;
       this.selected = selected;
       this.type = type;
       this.comRoleses = comRoleses;
       this.comMenuses = comMenuses;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=5)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parent")
    public ComMenus getComMenus() {
        return this.comMenus;
    }
    
    public void setComMenus(ComMenus comMenus) {
        this.comMenus = comMenus;
    }

    
    @Column(name="enable", length=2)
    public String getEnable() {
        return this.enable;
    }
    
    public void setEnable(String enable) {
        this.enable = enable;
    }

    
    @Column(name="icon", length=100)
    public String getIcon() {
        return this.icon;
    }
    
    public void setIcon(String icon) {
        this.icon = icon;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="msgkey", length=200)
    public String getMsgkey() {
        return this.msgkey;
    }
    
    public void setMsgkey(String msgkey) {
        this.msgkey = msgkey;
    }

    
    @Column(name="ordre")
    public Integer getOrdre() {
        return this.ordre;
    }
    
    public void setOrdre(Integer ordre) {
        this.ordre = ordre;
    }

    
    @Column(name="page", length=100)
    public String getPage() {
        return this.page;
    }
    
    public void setPage(String page) {
        this.page = page;
    }

    
    @Column(name="selected")
    public Boolean getSelected() {
        return this.selected;
    }
    
    public void setSelected(Boolean selected) {
        this.selected = selected;
    }

    
    @Column(name="type", length=2)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comMenus")
    public Set<ComRoles> getComRoleses() {
        return this.comRoleses;
    }
    
    public void setComRoleses(Set<ComRoles> comRoleses) {
        this.comRoleses = comRoleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comMenus")
    public Set<ComMenus> getComMenuses() {
        return this.comMenuses;
    }
    
    public void setComMenuses(Set<ComMenus> comMenuses) {
        this.comMenuses = comMenuses;
    }




}


