package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ComProduitsFamilles generated by hbm2java
 */
@Entity
@Table(name="com_produits_familles"
    ,catalog="ankata_db"
)
public class ComProduitsFamilles  implements java.io.Serializable {


     private Long id;
     private String nom;

    public ComProduitsFamilles() {
    }

    public ComProduitsFamilles(String nom) {
       this.nom = nom;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="nom", length=200)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }




}


