package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.flotte.FltAssurancesComp;
import com.horus.ankata.core.domain.flotte.FltConducteurs;
import com.horus.ankata.core.domain.flotte.FltDdesInvsPers;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComPersonnes generated by hbm2java
 */
@Entity
@Table(name="com_personnes"
    ,catalog="ankata_db"
)
public class ComPersonnes  implements java.io.Serializable {


     private Long id;
     private ComCivilites comCivilites;
     private ComFonctions comFonctions;
     private ComPays comPays;
     private ComSitFams comSitFams;
     private ComStructures comStructures;
     private String adrAdresse;
     private String adrBp;
     private String adrEmail;
     private String adrFax;
     private String adrTel1;
     private String adrTel2;
     private String adrVille;
     private Date dateEntree;
     private Date dateNaissance;
     private Date dc;
     private Date du;
     private Boolean estNeVers;
     private String nationnalite;
     private String naturePers;
     private String neVers;
     private String nom;
     private String nomComplet;
     private Integer nordre;
     private String photo;
     private String prenom;
     private Double salaire;
     private String sexe;
     private String typePers;
     private Long ucid;
     private Long uuid;
     private String villeNaissance;
     private Set<FltAssurancesComp> fltAssurancesComps = new HashSet<FltAssurancesComp>(0);
     private Set<FltConducteurs> fltConducteurses = new HashSet<FltConducteurs>(0);
     private Set<ComClients> comClientses = new HashSet<ComClients>(0);
     private Set<ComUsers> comUserses = new HashSet<ComUsers>(0);
     private Set<ComFournisseurs> comFournisseurses = new HashSet<ComFournisseurs>(0);
     private Set<FltDdesInvsPers> fltDdesInvsPerses = new HashSet<FltDdesInvsPers>(0);

    public ComPersonnes() {
    }

    public ComPersonnes(ComCivilites comCivilites, ComFonctions comFonctions, ComPays comPays, ComSitFams comSitFams, ComStructures comStructures, String adrAdresse, String adrBp, String adrEmail, String adrFax, String adrTel1, String adrTel2, String adrVille, Date dateEntree, Date dateNaissance, Date dc, Date du, Boolean estNeVers, String nationnalite, String naturePers, String neVers, String nom, String nomComplet, Integer nordre, String photo, String prenom, Double salaire, String sexe, String typePers, Long ucid, Long uuid, String villeNaissance, Set<FltAssurancesComp> fltAssurancesComps, Set<FltConducteurs> fltConducteurses, Set<ComClients> comClientses, Set<ComUsers> comUserses, Set<ComFournisseurs> comFournisseurses, Set<FltDdesInvsPers> fltDdesInvsPerses) {
       this.comCivilites = comCivilites;
       this.comFonctions = comFonctions;
       this.comPays = comPays;
       this.comSitFams = comSitFams;
       this.comStructures = comStructures;
       this.adrAdresse = adrAdresse;
       this.adrBp = adrBp;
       this.adrEmail = adrEmail;
       this.adrFax = adrFax;
       this.adrTel1 = adrTel1;
       this.adrTel2 = adrTel2;
       this.adrVille = adrVille;
       this.dateEntree = dateEntree;
       this.dateNaissance = dateNaissance;
       this.dc = dc;
       this.du = du;
       this.estNeVers = estNeVers;
       this.nationnalite = nationnalite;
       this.naturePers = naturePers;
       this.neVers = neVers;
       this.nom = nom;
       this.nomComplet = nomComplet;
       this.nordre = nordre;
       this.photo = photo;
       this.prenom = prenom;
       this.salaire = salaire;
       this.sexe = sexe;
       this.typePers = typePers;
       this.ucid = ucid;
       this.uuid = uuid;
       this.villeNaissance = villeNaissance;
       this.fltAssurancesComps = fltAssurancesComps;
       this.fltConducteurses = fltConducteurses;
       this.comClientses = comClientses;
       this.comUserses = comUserses;
       this.comFournisseurses = comFournisseurses;
       this.fltDdesInvsPerses = fltDdesInvsPerses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="civilite")
    public ComCivilites getComCivilites() {
        return this.comCivilites;
    }
    
    public void setComCivilites(ComCivilites comCivilites) {
        this.comCivilites = comCivilites;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fonction")
    public ComFonctions getComFonctions() {
        return this.comFonctions;
    }
    
    public void setComFonctions(ComFonctions comFonctions) {
        this.comFonctions = comFonctions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pays_naissance")
    public ComPays getComPays() {
        return this.comPays;
    }
    
    public void setComPays(ComPays comPays) {
        this.comPays = comPays;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="situation_familiale")
    public ComSitFams getComSitFams() {
        return this.comSitFams;
    }
    
    public void setComSitFams(ComSitFams comSitFams) {
        this.comSitFams = comSitFams;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="structure")
    public ComStructures getComStructures() {
        return this.comStructures;
    }
    
    public void setComStructures(ComStructures comStructures) {
        this.comStructures = comStructures;
    }

    
    @Column(name="adr_adresse", length=200)
    public String getAdrAdresse() {
        return this.adrAdresse;
    }
    
    public void setAdrAdresse(String adrAdresse) {
        this.adrAdresse = adrAdresse;
    }

    
    @Column(name="adr_bp", length=20)
    public String getAdrBp() {
        return this.adrBp;
    }
    
    public void setAdrBp(String adrBp) {
        this.adrBp = adrBp;
    }

    
    @Column(name="adr_email", length=200)
    public String getAdrEmail() {
        return this.adrEmail;
    }
    
    public void setAdrEmail(String adrEmail) {
        this.adrEmail = adrEmail;
    }

    
    @Column(name="adr_fax", length=200)
    public String getAdrFax() {
        return this.adrFax;
    }
    
    public void setAdrFax(String adrFax) {
        this.adrFax = adrFax;
    }

    
    @Column(name="adr_tel1", length=100)
    public String getAdrTel1() {
        return this.adrTel1;
    }
    
    public void setAdrTel1(String adrTel1) {
        this.adrTel1 = adrTel1;
    }

    
    @Column(name="adr_tel2", length=200)
    public String getAdrTel2() {
        return this.adrTel2;
    }
    
    public void setAdrTel2(String adrTel2) {
        this.adrTel2 = adrTel2;
    }

    
    @Column(name="adr_ville", length=200)
    public String getAdrVille() {
        return this.adrVille;
    }
    
    public void setAdrVille(String adrVille) {
        this.adrVille = adrVille;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_entree", length=10)
    public Date getDateEntree() {
        return this.dateEntree;
    }
    
    public void setDateEntree(Date dateEntree) {
        this.dateEntree = dateEntree;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_naissance", length=10)
    public Date getDateNaissance() {
        return this.dateNaissance;
    }
    
    public void setDateNaissance(Date dateNaissance) {
        this.dateNaissance = dateNaissance;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dc", length=19)
    public Date getDc() {
        return this.dc;
    }
    
    public void setDc(Date dc) {
        this.dc = dc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="du", length=19)
    public Date getDu() {
        return this.du;
    }
    
    public void setDu(Date du) {
        this.du = du;
    }

    
    @Column(name="est_ne_vers")
    public Boolean getEstNeVers() {
        return this.estNeVers;
    }
    
    public void setEstNeVers(Boolean estNeVers) {
        this.estNeVers = estNeVers;
    }

    
    @Column(name="nationnalite", length=50)
    public String getNationnalite() {
        return this.nationnalite;
    }
    
    public void setNationnalite(String nationnalite) {
        this.nationnalite = nationnalite;
    }

    
    @Column(name="nature_pers", length=2)
    public String getNaturePers() {
        return this.naturePers;
    }
    
    public void setNaturePers(String naturePers) {
        this.naturePers = naturePers;
    }

    
    @Column(name="ne_vers", length=200)
    public String getNeVers() {
        return this.neVers;
    }
    
    public void setNeVers(String neVers) {
        this.neVers = neVers;
    }

    
    @Column(name="nom", length=200)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="nom_complet", length=200)
    public String getNomComplet() {
        return this.nomComplet;
    }
    
    public void setNomComplet(String nomComplet) {
        this.nomComplet = nomComplet;
    }

    
    @Column(name="nordre")
    public Integer getNordre() {
        return this.nordre;
    }
    
    public void setNordre(Integer nordre) {
        this.nordre = nordre;
    }

    
    @Column(name="photo", length=200)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    
    @Column(name="prenom", length=200)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="salaire", precision=22, scale=0)
    public Double getSalaire() {
        return this.salaire;
    }
    
    public void setSalaire(Double salaire) {
        this.salaire = salaire;
    }

    
    @Column(name="sexe", length=2)
    public String getSexe() {
        return this.sexe;
    }
    
    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    
    @Column(name="type_pers", length=2)
    public String getTypePers() {
        return this.typePers;
    }
    
    public void setTypePers(String typePers) {
        this.typePers = typePers;
    }

    
    @Column(name="ucid")
    public Long getUcid() {
        return this.ucid;
    }
    
    public void setUcid(Long ucid) {
        this.ucid = ucid;
    }

    
    @Column(name="uuid")
    public Long getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Long uuid) {
        this.uuid = uuid;
    }

    
    @Column(name="ville_naissance", length=200)
    public String getVilleNaissance() {
        return this.villeNaissance;
    }
    
    public void setVilleNaissance(String villeNaissance) {
        this.villeNaissance = villeNaissance;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comPersonnes")
    public Set<FltAssurancesComp> getFltAssurancesComps() {
        return this.fltAssurancesComps;
    }
    
    public void setFltAssurancesComps(Set<FltAssurancesComp> fltAssurancesComps) {
        this.fltAssurancesComps = fltAssurancesComps;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comPersonnes")
    public Set<FltConducteurs> getFltConducteurses() {
        return this.fltConducteurses;
    }
    
    public void setFltConducteurses(Set<FltConducteurs> fltConducteurses) {
        this.fltConducteurses = fltConducteurses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comPersonnes")
    public Set<ComClients> getComClientses() {
        return this.comClientses;
    }
    
    public void setComClientses(Set<ComClients> comClientses) {
        this.comClientses = comClientses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comPersonnes")
    public Set<ComUsers> getComUserses() {
        return this.comUserses;
    }
    
    public void setComUserses(Set<ComUsers> comUserses) {
        this.comUserses = comUserses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comPersonnes")
    public Set<ComFournisseurs> getComFournisseurses() {
        return this.comFournisseurses;
    }
    
    public void setComFournisseurses(Set<ComFournisseurs> comFournisseurses) {
        this.comFournisseurses = comFournisseurses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comPersonnes")
    public Set<FltDdesInvsPers> getFltDdesInvsPerses() {
        return this.fltDdesInvsPerses;
    }
    
    public void setFltDdesInvsPerses(Set<FltDdesInvsPers> fltDdesInvsPerses) {
        this.fltDdesInvsPerses = fltDdesInvsPerses;
    }




}


