package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.vente.VteBonsLivraisonsLignes;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComProduits generated by hbm2java
 */
@Entity
@Table(name="com_produits"
    ,catalog="ankata_db"
)
public class ComProduits  implements java.io.Serializable {


     private Long id;
     private String code;
     private Long famille;
     private String nom;
     private Double tva;
     private String unite;
     private Set<VteBonsLivraisonsLignes> vteBonsLivraisonsLigneses = new HashSet<VteBonsLivraisonsLignes>(0);

    public ComProduits() {
    }

    public ComProduits(String code, Long famille, String nom, Double tva, String unite, Set<VteBonsLivraisonsLignes> vteBonsLivraisonsLigneses) {
       this.code = code;
       this.famille = famille;
       this.nom = nom;
       this.tva = tva;
       this.unite = unite;
       this.vteBonsLivraisonsLigneses = vteBonsLivraisonsLigneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="code", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="famille")
    public Long getFamille() {
        return this.famille;
    }
    
    public void setFamille(Long famille) {
        this.famille = famille;
    }

    
    @Column(name="nom", length=200)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="tva", precision=22, scale=0)
    public Double getTva() {
        return this.tva;
    }
    
    public void setTva(Double tva) {
        this.tva = tva;
    }

    
    @Column(name="unite", length=20)
    public String getUnite() {
        return this.unite;
    }
    
    public void setUnite(String unite) {
        this.unite = unite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comProduits")
    public Set<VteBonsLivraisonsLignes> getVteBonsLivraisonsLigneses() {
        return this.vteBonsLivraisonsLigneses;
    }
    
    public void setVteBonsLivraisonsLigneses(Set<VteBonsLivraisonsLignes> vteBonsLivraisonsLigneses) {
        this.vteBonsLivraisonsLigneses = vteBonsLivraisonsLigneses;
    }




}


