package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComParametres generated by hbm2java
 */
@Entity
@Table(name="com_parametres"
    ,catalog="ankata_db"
)
public class ComParametres  implements java.io.Serializable {


     private String code;
     private Date dc;
     private Date du;
     private String format;
     private String libelle;
     private String type;
     private Long ucid;
     private Long uuid;
     private String valeurs;
     private String value;

    public ComParametres() {
    }

	
    public ComParametres(String code) {
        this.code = code;
    }
    public ComParametres(String code, Date dc, Date du, String format, String libelle, String type, Long ucid, Long uuid, String valeurs, String value) {
       this.code = code;
       this.dc = dc;
       this.du = du;
       this.format = format;
       this.libelle = libelle;
       this.type = type;
       this.ucid = ucid;
       this.uuid = uuid;
       this.valeurs = valeurs;
       this.value = value;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dc", length=19)
    public Date getDc() {
        return this.dc;
    }
    
    public void setDc(Date dc) {
        this.dc = dc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="du", length=19)
    public Date getDu() {
        return this.du;
    }
    
    public void setDu(Date du) {
        this.du = du;
    }

    
    @Column(name="format", length=20)
    public String getFormat() {
        return this.format;
    }
    
    public void setFormat(String format) {
        this.format = format;
    }

    
    @Column(name="libelle", length=250)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="type", length=20)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    
    @Column(name="ucid")
    public Long getUcid() {
        return this.ucid;
    }
    
    public void setUcid(Long ucid) {
        this.ucid = ucid;
    }

    
    @Column(name="uuid")
    public Long getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Long uuid) {
        this.uuid = uuid;
    }

    
    @Column(name="valeurs")
    public String getValeurs() {
        return this.valeurs;
    }
    
    public void setValeurs(String valeurs) {
        this.valeurs = valeurs;
    }

    
    @Column(name="value", length=50)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


