package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ComPays generated by hbm2java
 */
@Entity
@Table(name="com_pays"
    ,catalog="ankata_db"
)
public class ComPays  implements java.io.Serializable {


     private String code;
     private ComMonnaies comMonnaies;
     private String devise;
     private String nationnalite;
     private String nom;
     private Set<ComLocalites> comLocaliteses = new HashSet<ComLocalites>(0);
     private Set<ComPersonnes> comPersonneses = new HashSet<ComPersonnes>(0);
     private Set<ComStructures> comStructureses = new HashSet<ComStructures>(0);

    public ComPays() {
    }

	
    public ComPays(String code) {
        this.code = code;
    }
    public ComPays(String code, ComMonnaies comMonnaies, String devise, String nationnalite, String nom, Set<ComLocalites> comLocaliteses, Set<ComPersonnes> comPersonneses, Set<ComStructures> comStructureses) {
       this.code = code;
       this.comMonnaies = comMonnaies;
       this.devise = devise;
       this.nationnalite = nationnalite;
       this.nom = nom;
       this.comLocaliteses = comLocaliteses;
       this.comPersonneses = comPersonneses;
       this.comStructureses = comStructureses;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false, length=3)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="monnaie")
    public ComMonnaies getComMonnaies() {
        return this.comMonnaies;
    }
    
    public void setComMonnaies(ComMonnaies comMonnaies) {
        this.comMonnaies = comMonnaies;
    }

    
    @Column(name="devise")
    public String getDevise() {
        return this.devise;
    }
    
    public void setDevise(String devise) {
        this.devise = devise;
    }

    
    @Column(name="nationnalite", length=50)
    public String getNationnalite() {
        return this.nationnalite;
    }
    
    public void setNationnalite(String nationnalite) {
        this.nationnalite = nationnalite;
    }

    
    @Column(name="nom", length=20)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comPays")
    public Set<ComLocalites> getComLocaliteses() {
        return this.comLocaliteses;
    }
    
    public void setComLocaliteses(Set<ComLocalites> comLocaliteses) {
        this.comLocaliteses = comLocaliteses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comPays")
    public Set<ComPersonnes> getComPersonneses() {
        return this.comPersonneses;
    }
    
    public void setComPersonneses(Set<ComPersonnes> comPersonneses) {
        this.comPersonneses = comPersonneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comPays")
    public Set<ComStructures> getComStructureses() {
        return this.comStructureses;
    }
    
    public void setComStructureses(Set<ComStructures> comStructureses) {
        this.comStructureses = comStructureses;
    }




}


