package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComUsers generated by hbm2java
 */
@Entity
@Table(name="com_users"
    ,catalog="ankata_db"
)
public class ComUsers  implements java.io.Serializable {


     private Long id;
     private ComPersonnes comPersonnes;
     private String changeMdp;
     private Date dc;
     private Date du;
     private String enable;
     private String login;
     private String mail;
     private String mdp;
     private String nom;
     private String prenom;
     private String status;
     private String structure;
     private String tel;
     private Long ucid;
     private Long uuid;
     private Set<ComProfilsUsers> comProfilsUserses = new HashSet<ComProfilsUsers>(0);
     private Set<ComPisteAudit> comPisteAudits = new HashSet<ComPisteAudit>(0);

    public ComUsers() {
    }

    public ComUsers(ComPersonnes comPersonnes, String changeMdp, Date dc, Date du, String enable, String login, String mail, String mdp, String nom, String prenom, String status, String structure, String tel, Long ucid, Long uuid, Set<ComProfilsUsers> comProfilsUserses, Set<ComPisteAudit> comPisteAudits) {
       this.comPersonnes = comPersonnes;
       this.changeMdp = changeMdp;
       this.dc = dc;
       this.du = du;
       this.enable = enable;
       this.login = login;
       this.mail = mail;
       this.mdp = mdp;
       this.nom = nom;
       this.prenom = prenom;
       this.status = status;
       this.structure = structure;
       this.tel = tel;
       this.ucid = ucid;
       this.uuid = uuid;
       this.comProfilsUserses = comProfilsUserses;
       this.comPisteAudits = comPisteAudits;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="personne")
    public ComPersonnes getComPersonnes() {
        return this.comPersonnes;
    }
    
    public void setComPersonnes(ComPersonnes comPersonnes) {
        this.comPersonnes = comPersonnes;
    }

    
    @Column(name="change_mdp", length=2)
    public String getChangeMdp() {
        return this.changeMdp;
    }
    
    public void setChangeMdp(String changeMdp) {
        this.changeMdp = changeMdp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dc", length=19)
    public Date getDc() {
        return this.dc;
    }
    
    public void setDc(Date dc) {
        this.dc = dc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="du", length=19)
    public Date getDu() {
        return this.du;
    }
    
    public void setDu(Date du) {
        this.du = du;
    }

    
    @Column(name="enable", length=2)
    public String getEnable() {
        return this.enable;
    }
    
    public void setEnable(String enable) {
        this.enable = enable;
    }

    
    @Column(name="login", length=20)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="mail", length=50)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    
    @Column(name="mdp", length=50)
    public String getMdp() {
        return this.mdp;
    }
    
    public void setMdp(String mdp) {
        this.mdp = mdp;
    }

    
    @Column(name="nom", length=250)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="prenom", length=250)
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    
    @Column(name="status", length=20)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="structure", length=20)
    public String getStructure() {
        return this.structure;
    }
    
    public void setStructure(String structure) {
        this.structure = structure;
    }

    
    @Column(name="tel", length=20)
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }

    
    @Column(name="ucid")
    public Long getUcid() {
        return this.ucid;
    }
    
    public void setUcid(Long ucid) {
        this.ucid = ucid;
    }

    
    @Column(name="uuid")
    public Long getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Long uuid) {
        this.uuid = uuid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comUsers")
    public Set<ComProfilsUsers> getComProfilsUserses() {
        return this.comProfilsUserses;
    }
    
    public void setComProfilsUserses(Set<ComProfilsUsers> comProfilsUserses) {
        this.comProfilsUserses = comProfilsUserses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comUsers")
    public Set<ComPisteAudit> getComPisteAudits() {
        return this.comPisteAudits;
    }
    
    public void setComPisteAudits(Set<ComPisteAudit> comPisteAudits) {
        this.comPisteAudits = comPisteAudits;
    }




}


