package com.horus.ankata.core.domain.achat;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComFournisseurs;
import com.horus.ankata.core.domain.commons.ComTypesPayements;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AchFactures generated by hbm2java
 */
@Entity
@Table(name="ach_factures"
    ,catalog="ankata_db"
)
public class AchFactures  implements java.io.Serializable {


     private Long id;
     private ComFournisseurs comFournisseurs;
     private ComTypesPayements comTypesPayements;
     private Date dateFac;
     private Double montantHt;
     private Double montantTtc;
     private Double montantTva;
     private String numFac;
     private String numFacFrs;
     private Byte paye;
     private Double tva;
     private Set<AchFacturesLignes> achFacturesLigneses = new HashSet<AchFacturesLignes>(0);

    public AchFactures() {
    }

    public AchFactures(ComFournisseurs comFournisseurs, ComTypesPayements comTypesPayements, Date dateFac, Double montantHt, Double montantTtc, Double montantTva, String numFac, String numFacFrs, Byte paye, Double tva, Set<AchFacturesLignes> achFacturesLigneses) {
       this.comFournisseurs = comFournisseurs;
       this.comTypesPayements = comTypesPayements;
       this.dateFac = dateFac;
       this.montantHt = montantHt;
       this.montantTtc = montantTtc;
       this.montantTva = montantTva;
       this.numFac = numFac;
       this.numFacFrs = numFacFrs;
       this.paye = paye;
       this.tva = tva;
       this.achFacturesLigneses = achFacturesLigneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fournisseur")
    public ComFournisseurs getComFournisseurs() {
        return this.comFournisseurs;
    }
    
    public void setComFournisseurs(ComFournisseurs comFournisseurs) {
        this.comFournisseurs = comFournisseurs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_paiement")
    public ComTypesPayements getComTypesPayements() {
        return this.comTypesPayements;
    }
    
    public void setComTypesPayements(ComTypesPayements comTypesPayements) {
        this.comTypesPayements = comTypesPayements;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_fac", length=10)
    public Date getDateFac() {
        return this.dateFac;
    }
    
    public void setDateFac(Date dateFac) {
        this.dateFac = dateFac;
    }

    
    @Column(name="montant_ht", precision=22, scale=0)
    public Double getMontantHt() {
        return this.montantHt;
    }
    
    public void setMontantHt(Double montantHt) {
        this.montantHt = montantHt;
    }

    
    @Column(name="montant_ttc", precision=22, scale=0)
    public Double getMontantTtc() {
        return this.montantTtc;
    }
    
    public void setMontantTtc(Double montantTtc) {
        this.montantTtc = montantTtc;
    }

    
    @Column(name="montant_tva", precision=22, scale=0)
    public Double getMontantTva() {
        return this.montantTva;
    }
    
    public void setMontantTva(Double montantTva) {
        this.montantTva = montantTva;
    }

    
    @Column(name="num_fac", length=45)
    public String getNumFac() {
        return this.numFac;
    }
    
    public void setNumFac(String numFac) {
        this.numFac = numFac;
    }

    
    @Column(name="num_fac_frs", length=20)
    public String getNumFacFrs() {
        return this.numFacFrs;
    }
    
    public void setNumFacFrs(String numFacFrs) {
        this.numFacFrs = numFacFrs;
    }

    
    @Column(name="paye")
    public Byte getPaye() {
        return this.paye;
    }
    
    public void setPaye(Byte paye) {
        this.paye = paye;
    }

    
    @Column(name="tva", precision=22, scale=0)
    public Double getTva() {
        return this.tva;
    }
    
    public void setTva(Double tva) {
        this.tva = tva;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="achFactures")
    public Set<AchFacturesLignes> getAchFacturesLigneses() {
        return this.achFacturesLigneses;
    }
    
    public void setAchFacturesLigneses(Set<AchFacturesLignes> achFacturesLigneses) {
        this.achFacturesLigneses = achFacturesLigneses;
    }




}


