package com.horus.ankata.core.domain.achat;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.stock.StkArticles;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AchDemandesLignes generated by hbm2java
 */
@Entity
@Table(name="ach_demandes_lignes"
    ,catalog="ankata_db"
)
public class AchDemandesLignes  implements java.io.Serializable {


     private Long id;
     private AchDemandes achDemandes;
     private StkArticles stkArticles;
     private String designation;
     private Double qte;
     private String unite;

    public AchDemandesLignes() {
    }

    public AchDemandesLignes(AchDemandes achDemandes, StkArticles stkArticles, String designation, Double qte, String unite) {
       this.achDemandes = achDemandes;
       this.stkArticles = stkArticles;
       this.designation = designation;
       this.qte = qte;
       this.unite = unite;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="demande")
    public AchDemandes getAchDemandes() {
        return this.achDemandes;
    }
    
    public void setAchDemandes(AchDemandes achDemandes) {
        this.achDemandes = achDemandes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="article")
    public StkArticles getStkArticles() {
        return this.stkArticles;
    }
    
    public void setStkArticles(StkArticles stkArticles) {
        this.stkArticles = stkArticles;
    }

    
    @Column(name="designation", length=300)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    
    @Column(name="qte", precision=22, scale=0)
    public Double getQte() {
        return this.qte;
    }
    
    public void setQte(Double qte) {
        this.qte = qte;
    }

    
    @Column(name="unite", length=20)
    public String getUnite() {
        return this.unite;
    }
    
    public void setUnite(String unite) {
        this.unite = unite;
    }




}


