package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FltConducteursRoles generated by hbm2java
 */
@Entity
@Table(name="flt_conducteurs_roles"
    ,catalog="ankata_db"
)
public class FltConducteursRoles  implements java.io.Serializable {


     private String code;
     private String libelle;
     private Set<FltMissionsConducteurs> fltMissionsConducteurses = new HashSet<FltMissionsConducteurs>(0);

    public FltConducteursRoles() {
    }

	
    public FltConducteursRoles(String code) {
        this.code = code;
    }
    public FltConducteursRoles(String code, String libelle, Set<FltMissionsConducteurs> fltMissionsConducteurses) {
       this.code = code;
       this.libelle = libelle;
       this.fltMissionsConducteurses = fltMissionsConducteurses;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=50)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltConducteursRoles")
    public Set<FltMissionsConducteurs> getFltMissionsConducteurses() {
        return this.fltMissionsConducteurses;
    }
    
    public void setFltMissionsConducteurses(Set<FltMissionsConducteurs> fltMissionsConducteurses) {
        this.fltMissionsConducteurses = fltMissionsConducteurses;
    }




}


