package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.stock.StkArticles;
import com.horus.ankata.core.domain.stock.StkBonsSorties;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FltDdesInvsPieces generated by hbm2java
 */
@Entity
@Table(name="flt_ddes_invs_pieces"
    ,catalog="ankata_db"
)
public class FltDdesInvsPieces  implements java.io.Serializable {


     private Long id;
     private FltDdesInvs fltDdesInvs;
     private StkArticles stkArticles;
     private StkBonsSorties stkBonsSorties;
     private String designation;
     private Double montantHt;
     private Double montantTtc;
     private Double pu;
     private Double qte;
     private Double tva;

    public FltDdesInvsPieces() {
    }

    public FltDdesInvsPieces(FltDdesInvs fltDdesInvs, StkArticles stkArticles, StkBonsSorties stkBonsSorties, String designation, Double montantHt, Double montantTtc, Double pu, Double qte, Double tva) {
       this.fltDdesInvs = fltDdesInvs;
       this.stkArticles = stkArticles;
       this.stkBonsSorties = stkBonsSorties;
       this.designation = designation;
       this.montantHt = montantHt;
       this.montantTtc = montantTtc;
       this.pu = pu;
       this.qte = qte;
       this.tva = tva;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="demande")
    public FltDdesInvs getFltDdesInvs() {
        return this.fltDdesInvs;
    }
    
    public void setFltDdesInvs(FltDdesInvs fltDdesInvs) {
        this.fltDdesInvs = fltDdesInvs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="piece")
    public StkArticles getStkArticles() {
        return this.stkArticles;
    }
    
    public void setStkArticles(StkArticles stkArticles) {
        this.stkArticles = stkArticles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bon_sortie")
    public StkBonsSorties getStkBonsSorties() {
        return this.stkBonsSorties;
    }
    
    public void setStkBonsSorties(StkBonsSorties stkBonsSorties) {
        this.stkBonsSorties = stkBonsSorties;
    }

    
    @Column(name="designation", length=200)
    public String getDesignation() {
        return this.designation;
    }
    
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    
    @Column(name="montant_ht", precision=22, scale=0)
    public Double getMontantHt() {
        return this.montantHt;
    }
    
    public void setMontantHt(Double montantHt) {
        this.montantHt = montantHt;
    }

    
    @Column(name="montant_ttc", precision=22, scale=0)
    public Double getMontantTtc() {
        return this.montantTtc;
    }
    
    public void setMontantTtc(Double montantTtc) {
        this.montantTtc = montantTtc;
    }

    
    @Column(name="pu", precision=22, scale=0)
    public Double getPu() {
        return this.pu;
    }
    
    public void setPu(Double pu) {
        this.pu = pu;
    }

    
    @Column(name="qte", precision=22, scale=0)
    public Double getQte() {
        return this.qte;
    }
    
    public void setQte(Double qte) {
        this.qte = qte;
    }

    
    @Column(name="tva", precision=22, scale=0)
    public Double getTva() {
        return this.tva;
    }
    
    public void setTva(Double tva) {
        this.tva = tva;
    }




}


