package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FltDdesInvsTypes generated by hbm2java
 */
@Entity
@Table(name="flt_ddes_invs_types"
    ,catalog="ankata_db"
)
public class FltDdesInvsTypes  implements java.io.Serializable {


     private String code;
     private String libelle;
     private Set<FltDdesInvs> fltDdesInvses = new HashSet<FltDdesInvs>(0);

    public FltDdesInvsTypes() {
    }

	
    public FltDdesInvsTypes(String code) {
        this.code = code;
    }
    public FltDdesInvsTypes(String code, String libelle, Set<FltDdesInvs> fltDdesInvses) {
       this.code = code;
       this.libelle = libelle;
       this.fltDdesInvses = fltDdesInvses;
    }
   
     @Id 

    
    @Column(name="code", unique=true, nullable=false)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltDdesInvsTypes")
    public Set<FltDdesInvs> getFltDdesInvses() {
        return this.fltDdesInvses;
    }
    
    public void setFltDdesInvses(Set<FltDdesInvs> fltDdesInvses) {
        this.fltDdesInvses = fltDdesInvses;
    }




}


