package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FltMissionsInfractions generated by hbm2java
 */
@Entity
@Table(name="flt_missions_infractions"
    ,catalog="ankata_db"
)
public class FltMissionsInfractions  implements java.io.Serializable {


     private Long id;
     private FltMissions fltMissions;
     private FltTypesInfractions fltTypesInfractions;
     private Double amende;
     private Double fraisDivers;
     private String libelle;
     private Boolean retraitPapier;
     private Boolean retraitVehicule;

    public FltMissionsInfractions() {
    }

    public FltMissionsInfractions(FltMissions fltMissions, FltTypesInfractions fltTypesInfractions, Double amende, Double fraisDivers, String libelle, Boolean retraitPapier, Boolean retraitVehicule) {
       this.fltMissions = fltMissions;
       this.fltTypesInfractions = fltTypesInfractions;
       this.amende = amende;
       this.fraisDivers = fraisDivers;
       this.libelle = libelle;
       this.retraitPapier = retraitPapier;
       this.retraitVehicule = retraitVehicule;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mission")
    public FltMissions getFltMissions() {
        return this.fltMissions;
    }
    
    public void setFltMissions(FltMissions fltMissions) {
        this.fltMissions = fltMissions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_infraction")
    public FltTypesInfractions getFltTypesInfractions() {
        return this.fltTypesInfractions;
    }
    
    public void setFltTypesInfractions(FltTypesInfractions fltTypesInfractions) {
        this.fltTypesInfractions = fltTypesInfractions;
    }

    
    @Column(name="amende", precision=22, scale=0)
    public Double getAmende() {
        return this.amende;
    }
    
    public void setAmende(Double amende) {
        this.amende = amende;
    }

    
    @Column(name="frais_divers", precision=22, scale=0)
    public Double getFraisDivers() {
        return this.fraisDivers;
    }
    
    public void setFraisDivers(Double fraisDivers) {
        this.fraisDivers = fraisDivers;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="retrait_papier")
    public Boolean getRetraitPapier() {
        return this.retraitPapier;
    }
    
    public void setRetraitPapier(Boolean retraitPapier) {
        this.retraitPapier = retraitPapier;
    }

    
    @Column(name="retrait_vehicule")
    public Boolean getRetraitVehicule() {
        return this.retraitVehicule;
    }
    
    public void setRetraitVehicule(Boolean retraitVehicule) {
        this.retraitVehicule = retraitVehicule;
    }




}


