package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FltMarques generated by hbm2java
 */
@Entity
@Table(name="flt_marques"
    ,catalog="ankata_db"
)
public class FltMarques  implements java.io.Serializable {


     private Long id;
     private String code;
     private String icone;
     private String libelle;
     private String statut;
     private Set<FltModeles> fltModeleses = new HashSet<FltModeles>(0);

    public FltMarques() {
    }

    public FltMarques(String code, String icone, String libelle, String statut, Set<FltModeles> fltModeleses) {
       this.code = code;
       this.icone = icone;
       this.libelle = libelle;
       this.statut = statut;
       this.fltModeleses = fltModeleses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="code", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="icone", length=100)
    public String getIcone() {
        return this.icone;
    }
    
    public void setIcone(String icone) {
        this.icone = icone;
    }

    
    @Column(name="libelle", length=250)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="statut", length=2)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltMarques")
    public Set<FltModeles> getFltModeleses() {
        return this.fltModeleses;
    }
    
    public void setFltModeleses(Set<FltModeles> fltModeleses) {
        this.fltModeleses = fltModeleses;
    }




}


