package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComFournisseurs;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FltMissionsCharges generated by hbm2java
 */
@Entity
@Table(name="flt_missions_charges"
    ,catalog="ankata_db"
)
public class FltMissionsCharges  implements java.io.Serializable {


     private Long id;
     private ComFournisseurs comFournisseurs;
     private FltMissions fltMissions;
     private FltTypesCharges fltTypesCharges;
     private Date dateEnreg;
     private Double montant;
     private String observation;
     private Double pu;
     private Double qte;

    public FltMissionsCharges() {
    }

    public FltMissionsCharges(ComFournisseurs comFournisseurs, FltMissions fltMissions, FltTypesCharges fltTypesCharges, Date dateEnreg, Double montant, String observation, Double pu, Double qte) {
       this.comFournisseurs = comFournisseurs;
       this.fltMissions = fltMissions;
       this.fltTypesCharges = fltTypesCharges;
       this.dateEnreg = dateEnreg;
       this.montant = montant;
       this.observation = observation;
       this.pu = pu;
       this.qte = qte;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="founisseur")
    public ComFournisseurs getComFournisseurs() {
        return this.comFournisseurs;
    }
    
    public void setComFournisseurs(ComFournisseurs comFournisseurs) {
        this.comFournisseurs = comFournisseurs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mission")
    public FltMissions getFltMissions() {
        return this.fltMissions;
    }
    
    public void setFltMissions(FltMissions fltMissions) {
        this.fltMissions = fltMissions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_chage")
    public FltTypesCharges getFltTypesCharges() {
        return this.fltTypesCharges;
    }
    
    public void setFltTypesCharges(FltTypesCharges fltTypesCharges) {
        this.fltTypesCharges = fltTypesCharges;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_enreg", length=10)
    public Date getDateEnreg() {
        return this.dateEnreg;
    }
    
    public void setDateEnreg(Date dateEnreg) {
        this.dateEnreg = dateEnreg;
    }

    
    @Column(name="montant", precision=22, scale=0)
    public Double getMontant() {
        return this.montant;
    }
    
    public void setMontant(Double montant) {
        this.montant = montant;
    }

    
    @Column(name="observation")
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }

    
    @Column(name="pu", precision=22, scale=0)
    public Double getPu() {
        return this.pu;
    }
    
    public void setPu(Double pu) {
        this.pu = pu;
    }

    
    @Column(name="qte", precision=22, scale=0)
    public Double getQte() {
        return this.qte;
    }
    
    public void setQte(Double qte) {
        this.qte = qte;
    }




}


