package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FltMissionsConducteurs generated by hbm2java
 */
@Entity
@Table(name="flt_missions_conducteurs"
    ,catalog="ankata_db"
)
public class FltMissionsConducteurs  implements java.io.Serializable {


     private Long id;
     private FltConducteurs fltConducteurs;
     private FltConducteursRoles fltConducteursRoles;
     private FltMissions fltMissions;

    public FltMissionsConducteurs() {
    }

    public FltMissionsConducteurs(FltConducteurs fltConducteurs, FltConducteursRoles fltConducteursRoles, FltMissions fltMissions) {
       this.fltConducteurs = fltConducteurs;
       this.fltConducteursRoles = fltConducteursRoles;
       this.fltMissions = fltMissions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="conducteur")
    public FltConducteurs getFltConducteurs() {
        return this.fltConducteurs;
    }
    
    public void setFltConducteurs(FltConducteurs fltConducteurs) {
        this.fltConducteurs = fltConducteurs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role")
    public FltConducteursRoles getFltConducteursRoles() {
        return this.fltConducteursRoles;
    }
    
    public void setFltConducteursRoles(FltConducteursRoles fltConducteursRoles) {
        this.fltConducteursRoles = fltConducteursRoles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mission")
    public FltMissions getFltMissions() {
        return this.fltMissions;
    }
    
    public void setFltMissions(FltMissions fltMissions) {
        this.fltMissions = fltMissions;
    }




}


