package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FltMissionsSinistres generated by hbm2java
 */
@Entity
@Table(name="flt_missions_sinistres"
    ,catalog="ankata_db"
)
public class FltMissionsSinistres  implements java.io.Serializable {


     private Long id;
     private FltMissions fltMissions;
     private Boolean constat;
     private Boolean corporel;
     private Date dateAcc;
     private String lieu;
     private Boolean materiel;
     private Boolean mortel;
     private Boolean rapport;

    public FltMissionsSinistres() {
    }

    public FltMissionsSinistres(FltMissions fltMissions, Boolean constat, Boolean corporel, Date dateAcc, String lieu, Boolean materiel, Boolean mortel, Boolean rapport) {
       this.fltMissions = fltMissions;
       this.constat = constat;
       this.corporel = corporel;
       this.dateAcc = dateAcc;
       this.lieu = lieu;
       this.materiel = materiel;
       this.mortel = mortel;
       this.rapport = rapport;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mission")
    public FltMissions getFltMissions() {
        return this.fltMissions;
    }
    
    public void setFltMissions(FltMissions fltMissions) {
        this.fltMissions = fltMissions;
    }

    
    @Column(name="constat")
    public Boolean getConstat() {
        return this.constat;
    }
    
    public void setConstat(Boolean constat) {
        this.constat = constat;
    }

    
    @Column(name="corporel")
    public Boolean getCorporel() {
        return this.corporel;
    }
    
    public void setCorporel(Boolean corporel) {
        this.corporel = corporel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_acc", length=10)
    public Date getDateAcc() {
        return this.dateAcc;
    }
    
    public void setDateAcc(Date dateAcc) {
        this.dateAcc = dateAcc;
    }

    
    @Column(name="lieu", length=200)
    public String getLieu() {
        return this.lieu;
    }
    
    public void setLieu(String lieu) {
        this.lieu = lieu;
    }

    
    @Column(name="materiel")
    public Boolean getMateriel() {
        return this.materiel;
    }
    
    public void setMateriel(Boolean materiel) {
        this.materiel = materiel;
    }

    
    @Column(name="mortel")
    public Boolean getMortel() {
        return this.mortel;
    }
    
    public void setMortel(Boolean mortel) {
        this.mortel = mortel;
    }

    
    @Column(name="rapport")
    public Boolean getRapport() {
        return this.rapport;
    }
    
    public void setRapport(Boolean rapport) {
        this.rapport = rapport;
    }




}


