package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FltTypesEntretiens generated by hbm2java
 */
@Entity
@Table(name="flt_types_entretiens"
    ,catalog="ankata_db"
)
public class FltTypesEntretiens  implements java.io.Serializable {


     private Long id;
     private String libelle;
     private Set<FltMissionsEntretiens> fltMissionsEntretienses = new HashSet<FltMissionsEntretiens>(0);

    public FltTypesEntretiens() {
    }

    public FltTypesEntretiens(String libelle, Set<FltMissionsEntretiens> fltMissionsEntretienses) {
       this.libelle = libelle;
       this.fltMissionsEntretienses = fltMissionsEntretienses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltTypesEntretiens")
    public Set<FltMissionsEntretiens> getFltMissionsEntretienses() {
        return this.fltMissionsEntretienses;
    }
    
    public void setFltMissionsEntretienses(Set<FltMissionsEntretiens> fltMissionsEntretienses) {
        this.fltMissionsEntretienses = fltMissionsEntretienses;
    }




}


