package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.stock.StkBonsCommandesInternes;
import com.horus.ankata.core.domain.stock.StkBonsSorties;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FltVehicules generated by hbm2java
 */
@Entity
@Table(name="flt_vehicules"
    ,catalog="ankata_db"
)
public class FltVehicules  implements java.io.Serializable {


     private Long id;
     private FltAcquisitions fltAcquisitions;
     private FltConducteurs fltConducteurs;
     private FltModeles fltModeles;
     private FltParcs fltParcs;
     private FltVehiculesStatuts fltVehiculesStatuts;
     private String ancNumImm;
     private Integer annee;
     private Integer boiteVit;
     private String code;
     private String codeCle;
     private Double consExUrb;
     private Double consMix;
     private Double consUrb;
     private String couleur;
     private Integer cylindre;
     private Date dateEntreeParc;
     private Date dateMisCirc;
     private Date dateRestitution;
     private String dimensions;
     private Double emissCo2;
     private String energie;
     private String genre;
     private String icone;
     private String immatriculation;
     private Integer nbrePorte;
     private String numCarteGrise;
     private String numChassis;
     private String numImputation;
     private String numOrdre;
     private Double prix;
     private Integer ptc;
     private Integer ptv;
     private Integer puisAdm;
     private Integer puisReel;
     private Double vmax;
     private Integer volCoffMax;
     private Integer volCoffMin;
     private Set<FltVehiculesAttachements> fltVehiculesAttachementses = new HashSet<FltVehiculesAttachements>(0);
     private Set<FltAssurances> fltAssuranceses = new HashSet<FltAssurances>(0);
     private Set<FltVisitesTechniques> fltVisitesTechniqueses = new HashSet<FltVisitesTechniques>(0);
     private Set<StkBonsSorties> stkBonsSortieses = new HashSet<StkBonsSorties>(0);
     private Set<FltDdesInvs> fltDdesInvses = new HashSet<FltDdesInvs>(0);
     private Set<StkBonsCommandesInternes> stkBonsCommandesInterneses = new HashSet<StkBonsCommandesInternes>(0);
     private Set<FltVehiculesPhotos> fltVehiculesPhotoses = new HashSet<FltVehiculesPhotos>(0);
     private Set<FltMissions> fltMissionses = new HashSet<FltMissions>(0);
     private Set<FltReservation> fltReservations = new HashSet<FltReservation>(0);
     private Set<FltVignettes> fltVignetteses = new HashSet<FltVignettes>(0);

    public FltVehicules() {
    }

    public FltVehicules(FltAcquisitions fltAcquisitions, FltConducteurs fltConducteurs, FltModeles fltModeles, FltParcs fltParcs, FltVehiculesStatuts fltVehiculesStatuts, String ancNumImm, Integer annee, Integer boiteVit, String code, String codeCle, Double consExUrb, Double consMix, Double consUrb, String couleur, Integer cylindre, Date dateEntreeParc, Date dateMisCirc, Date dateRestitution, String dimensions, Double emissCo2, String energie, String genre, String icone, String immatriculation, Integer nbrePorte, String numCarteGrise, String numChassis, String numImputation, String numOrdre, Double prix, Integer ptc, Integer ptv, Integer puisAdm, Integer puisReel, Double vmax, Integer volCoffMax, Integer volCoffMin, Set<FltVehiculesAttachements> fltVehiculesAttachementses, Set<FltAssurances> fltAssuranceses, Set<FltVisitesTechniques> fltVisitesTechniqueses, Set<StkBonsSorties> stkBonsSortieses, Set<FltDdesInvs> fltDdesInvses, Set<StkBonsCommandesInternes> stkBonsCommandesInterneses, Set<FltVehiculesPhotos> fltVehiculesPhotoses, Set<FltMissions> fltMissionses, Set<FltReservation> fltReservations, Set<FltVignettes> fltVignetteses) {
       this.fltAcquisitions = fltAcquisitions;
       this.fltConducteurs = fltConducteurs;
       this.fltModeles = fltModeles;
       this.fltParcs = fltParcs;
       this.fltVehiculesStatuts = fltVehiculesStatuts;
       this.ancNumImm = ancNumImm;
       this.annee = annee;
       this.boiteVit = boiteVit;
       this.code = code;
       this.codeCle = codeCle;
       this.consExUrb = consExUrb;
       this.consMix = consMix;
       this.consUrb = consUrb;
       this.couleur = couleur;
       this.cylindre = cylindre;
       this.dateEntreeParc = dateEntreeParc;
       this.dateMisCirc = dateMisCirc;
       this.dateRestitution = dateRestitution;
       this.dimensions = dimensions;
       this.emissCo2 = emissCo2;
       this.energie = energie;
       this.genre = genre;
       this.icone = icone;
       this.immatriculation = immatriculation;
       this.nbrePorte = nbrePorte;
       this.numCarteGrise = numCarteGrise;
       this.numChassis = numChassis;
       this.numImputation = numImputation;
       this.numOrdre = numOrdre;
       this.prix = prix;
       this.ptc = ptc;
       this.ptv = ptv;
       this.puisAdm = puisAdm;
       this.puisReel = puisReel;
       this.vmax = vmax;
       this.volCoffMax = volCoffMax;
       this.volCoffMin = volCoffMin;
       this.fltVehiculesAttachementses = fltVehiculesAttachementses;
       this.fltAssuranceses = fltAssuranceses;
       this.fltVisitesTechniqueses = fltVisitesTechniqueses;
       this.stkBonsSortieses = stkBonsSortieses;
       this.fltDdesInvses = fltDdesInvses;
       this.stkBonsCommandesInterneses = stkBonsCommandesInterneses;
       this.fltVehiculesPhotoses = fltVehiculesPhotoses;
       this.fltMissionses = fltMissionses;
       this.fltReservations = fltReservations;
       this.fltVignetteses = fltVignetteses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="acquisition")
    public FltAcquisitions getFltAcquisitions() {
        return this.fltAcquisitions;
    }
    
    public void setFltAcquisitions(FltAcquisitions fltAcquisitions) {
        this.fltAcquisitions = fltAcquisitions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="conducteur")
    public FltConducteurs getFltConducteurs() {
        return this.fltConducteurs;
    }
    
    public void setFltConducteurs(FltConducteurs fltConducteurs) {
        this.fltConducteurs = fltConducteurs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="modele")
    public FltModeles getFltModeles() {
        return this.fltModeles;
    }
    
    public void setFltModeles(FltModeles fltModeles) {
        this.fltModeles = fltModeles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parc")
    public FltParcs getFltParcs() {
        return this.fltParcs;
    }
    
    public void setFltParcs(FltParcs fltParcs) {
        this.fltParcs = fltParcs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="statut_vehicule")
    public FltVehiculesStatuts getFltVehiculesStatuts() {
        return this.fltVehiculesStatuts;
    }
    
    public void setFltVehiculesStatuts(FltVehiculesStatuts fltVehiculesStatuts) {
        this.fltVehiculesStatuts = fltVehiculesStatuts;
    }

    
    @Column(name="anc_num_imm", length=50)
    public String getAncNumImm() {
        return this.ancNumImm;
    }
    
    public void setAncNumImm(String ancNumImm) {
        this.ancNumImm = ancNumImm;
    }

    
    @Column(name="annee")
    public Integer getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(Integer annee) {
        this.annee = annee;
    }

    
    @Column(name="boite_vit")
    public Integer getBoiteVit() {
        return this.boiteVit;
    }
    
    public void setBoiteVit(Integer boiteVit) {
        this.boiteVit = boiteVit;
    }

    
    @Column(name="code", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="code_cle", length=20)
    public String getCodeCle() {
        return this.codeCle;
    }
    
    public void setCodeCle(String codeCle) {
        this.codeCle = codeCle;
    }

    
    @Column(name="cons_ex_urb", precision=22, scale=0)
    public Double getConsExUrb() {
        return this.consExUrb;
    }
    
    public void setConsExUrb(Double consExUrb) {
        this.consExUrb = consExUrb;
    }

    
    @Column(name="cons_mix", precision=22, scale=0)
    public Double getConsMix() {
        return this.consMix;
    }
    
    public void setConsMix(Double consMix) {
        this.consMix = consMix;
    }

    
    @Column(name="cons_urb", precision=22, scale=0)
    public Double getConsUrb() {
        return this.consUrb;
    }
    
    public void setConsUrb(Double consUrb) {
        this.consUrb = consUrb;
    }

    
    @Column(name="couleur", length=20)
    public String getCouleur() {
        return this.couleur;
    }
    
    public void setCouleur(String couleur) {
        this.couleur = couleur;
    }

    
    @Column(name="cylindre")
    public Integer getCylindre() {
        return this.cylindre;
    }
    
    public void setCylindre(Integer cylindre) {
        this.cylindre = cylindre;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_entree_parc", length=10)
    public Date getDateEntreeParc() {
        return this.dateEntreeParc;
    }
    
    public void setDateEntreeParc(Date dateEntreeParc) {
        this.dateEntreeParc = dateEntreeParc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_mis_circ", length=10)
    public Date getDateMisCirc() {
        return this.dateMisCirc;
    }
    
    public void setDateMisCirc(Date dateMisCirc) {
        this.dateMisCirc = dateMisCirc;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_restitution", length=10)
    public Date getDateRestitution() {
        return this.dateRestitution;
    }
    
    public void setDateRestitution(Date dateRestitution) {
        this.dateRestitution = dateRestitution;
    }

    
    @Column(name="dimensions", length=20)
    public String getDimensions() {
        return this.dimensions;
    }
    
    public void setDimensions(String dimensions) {
        this.dimensions = dimensions;
    }

    
    @Column(name="emiss_co2", precision=22, scale=0)
    public Double getEmissCo2() {
        return this.emissCo2;
    }
    
    public void setEmissCo2(Double emissCo2) {
        this.emissCo2 = emissCo2;
    }

    
    @Column(name="energie", length=1)
    public String getEnergie() {
        return this.energie;
    }
    
    public void setEnergie(String energie) {
        this.energie = energie;
    }

    
    @Column(name="genre", length=20)
    public String getGenre() {
        return this.genre;
    }
    
    public void setGenre(String genre) {
        this.genre = genre;
    }

    
    @Column(name="icone", length=100)
    public String getIcone() {
        return this.icone;
    }
    
    public void setIcone(String icone) {
        this.icone = icone;
    }

    
    @Column(name="immatriculation", length=50)
    public String getImmatriculation() {
        return this.immatriculation;
    }
    
    public void setImmatriculation(String immatriculation) {
        this.immatriculation = immatriculation;
    }

    
    @Column(name="nbre_porte")
    public Integer getNbrePorte() {
        return this.nbrePorte;
    }
    
    public void setNbrePorte(Integer nbrePorte) {
        this.nbrePorte = nbrePorte;
    }

    
    @Column(name="num_carte_grise", length=50)
    public String getNumCarteGrise() {
        return this.numCarteGrise;
    }
    
    public void setNumCarteGrise(String numCarteGrise) {
        this.numCarteGrise = numCarteGrise;
    }

    
    @Column(name="num_chassis", length=20)
    public String getNumChassis() {
        return this.numChassis;
    }
    
    public void setNumChassis(String numChassis) {
        this.numChassis = numChassis;
    }

    
    @Column(name="num_imputation", length=50)
    public String getNumImputation() {
        return this.numImputation;
    }
    
    public void setNumImputation(String numImputation) {
        this.numImputation = numImputation;
    }

    
    @Column(name="num_ordre", length=20)
    public String getNumOrdre() {
        return this.numOrdre;
    }
    
    public void setNumOrdre(String numOrdre) {
        this.numOrdre = numOrdre;
    }

    
    @Column(name="prix", precision=22, scale=0)
    public Double getPrix() {
        return this.prix;
    }
    
    public void setPrix(Double prix) {
        this.prix = prix;
    }

    
    @Column(name="ptc")
    public Integer getPtc() {
        return this.ptc;
    }
    
    public void setPtc(Integer ptc) {
        this.ptc = ptc;
    }

    
    @Column(name="ptv")
    public Integer getPtv() {
        return this.ptv;
    }
    
    public void setPtv(Integer ptv) {
        this.ptv = ptv;
    }

    
    @Column(name="puis_adm")
    public Integer getPuisAdm() {
        return this.puisAdm;
    }
    
    public void setPuisAdm(Integer puisAdm) {
        this.puisAdm = puisAdm;
    }

    
    @Column(name="puis_reel")
    public Integer getPuisReel() {
        return this.puisReel;
    }
    
    public void setPuisReel(Integer puisReel) {
        this.puisReel = puisReel;
    }

    
    @Column(name="vmax", precision=22, scale=0)
    public Double getVmax() {
        return this.vmax;
    }
    
    public void setVmax(Double vmax) {
        this.vmax = vmax;
    }

    
    @Column(name="vol_coff_max")
    public Integer getVolCoffMax() {
        return this.volCoffMax;
    }
    
    public void setVolCoffMax(Integer volCoffMax) {
        this.volCoffMax = volCoffMax;
    }

    
    @Column(name="vol_coff_min")
    public Integer getVolCoffMin() {
        return this.volCoffMin;
    }
    
    public void setVolCoffMin(Integer volCoffMin) {
        this.volCoffMin = volCoffMin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltVehicules")
    public Set<FltVehiculesAttachements> getFltVehiculesAttachementses() {
        return this.fltVehiculesAttachementses;
    }
    
    public void setFltVehiculesAttachementses(Set<FltVehiculesAttachements> fltVehiculesAttachementses) {
        this.fltVehiculesAttachementses = fltVehiculesAttachementses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltVehicules")
    public Set<FltAssurances> getFltAssuranceses() {
        return this.fltAssuranceses;
    }
    
    public void setFltAssuranceses(Set<FltAssurances> fltAssuranceses) {
        this.fltAssuranceses = fltAssuranceses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltVehicules")
    public Set<FltVisitesTechniques> getFltVisitesTechniqueses() {
        return this.fltVisitesTechniqueses;
    }
    
    public void setFltVisitesTechniqueses(Set<FltVisitesTechniques> fltVisitesTechniqueses) {
        this.fltVisitesTechniqueses = fltVisitesTechniqueses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltVehicules")
    public Set<StkBonsSorties> getStkBonsSortieses() {
        return this.stkBonsSortieses;
    }
    
    public void setStkBonsSortieses(Set<StkBonsSorties> stkBonsSortieses) {
        this.stkBonsSortieses = stkBonsSortieses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltVehicules")
    public Set<FltDdesInvs> getFltDdesInvses() {
        return this.fltDdesInvses;
    }
    
    public void setFltDdesInvses(Set<FltDdesInvs> fltDdesInvses) {
        this.fltDdesInvses = fltDdesInvses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltVehicules")
    public Set<StkBonsCommandesInternes> getStkBonsCommandesInterneses() {
        return this.stkBonsCommandesInterneses;
    }
    
    public void setStkBonsCommandesInterneses(Set<StkBonsCommandesInternes> stkBonsCommandesInterneses) {
        this.stkBonsCommandesInterneses = stkBonsCommandesInterneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltVehicules")
    public Set<FltVehiculesPhotos> getFltVehiculesPhotoses() {
        return this.fltVehiculesPhotoses;
    }
    
    public void setFltVehiculesPhotoses(Set<FltVehiculesPhotos> fltVehiculesPhotoses) {
        this.fltVehiculesPhotoses = fltVehiculesPhotoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltVehicules")
    public Set<FltMissions> getFltMissionses() {
        return this.fltMissionses;
    }
    
    public void setFltMissionses(Set<FltMissions> fltMissionses) {
        this.fltMissionses = fltMissionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltVehicules")
    public Set<FltReservation> getFltReservations() {
        return this.fltReservations;
    }
    
    public void setFltReservations(Set<FltReservation> fltReservations) {
        this.fltReservations = fltReservations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltVehicules")
    public Set<FltVignettes> getFltVignetteses() {
        return this.fltVignetteses;
    }
    
    public void setFltVignetteses(Set<FltVignettes> fltVignetteses) {
        this.fltVignetteses = fltVignetteses;
    }




}


