package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FltVehiculesAttachements generated by hbm2java
 */
@Entity
@Table(name="flt_vehicules_attachements"
    ,catalog="ankata_db"
)
public class FltVehiculesAttachements  implements java.io.Serializable {


     private Long id;
     private FltVehicules fltVehicules;
     private String description;
     private String fichier;
     private String libelle;

    public FltVehiculesAttachements() {
    }

    public FltVehiculesAttachements(FltVehicules fltVehicules, String description, String fichier, String libelle) {
       this.fltVehicules = fltVehicules;
       this.description = description;
       this.fichier = fichier;
       this.libelle = libelle;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="vehicule")
    public FltVehicules getFltVehicules() {
        return this.fltVehicules;
    }
    
    public void setFltVehicules(FltVehicules fltVehicules) {
        this.fltVehicules = fltVehicules;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="fichier", length=20)
    public String getFichier() {
        return this.fichier;
    }
    
    public void setFichier(String fichier) {
        this.fichier = fichier;
    }

    
    @Column(name="libelle", length=200)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }




}


