package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FltActivites generated by hbm2java
 */
@Entity
@Table(name="flt_activites"
    ,catalog="ankata_db"
)
public class FltActivites  implements java.io.Serializable {


     private Long id;
     private String libelle;
     private Set<FltMissions> fltMissionses = new HashSet<FltMissions>(0);

    public FltActivites() {
    }

    public FltActivites(String libelle, Set<FltMissions> fltMissionses) {
       this.libelle = libelle;
       this.fltMissionses = fltMissionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="libelle", length=250)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltActivites")
    public Set<FltMissions> getFltMissionses() {
        return this.fltMissionses;
    }
    
    public void setFltMissionses(Set<FltMissions> fltMissionses) {
        this.fltMissionses = fltMissionses;
    }




}


