package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComUnites;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StkStocks generated by hbm2java
 */
@Entity
@Table(name="stk_stocks"
    ,catalog="ankata_db"
)
public class StkStocks  implements java.io.Serializable {


     private Long id;
     private ComUnites comUnites;
     private StkArticles stkArticles;
     private StkMagasins stkMagasins;
     private String commentaire;
     private Date dateBon;
     private String numBonCde;
     private String numBonLiv;
     private String numBonSti;
     private Double pu;
     private Double qte;
     private String typeMvt;
     private Set<StkStocksEntrees> stkStocksEntreeses = new HashSet<StkStocksEntrees>(0);
     private Set<StkStocksSorties> stkStocksSortieses = new HashSet<StkStocksSorties>(0);

    public StkStocks() {
    }

    public StkStocks(ComUnites comUnites, StkArticles stkArticles, StkMagasins stkMagasins, String commentaire, Date dateBon, String numBonCde, String numBonLiv, String numBonSti, Double pu, Double qte, String typeMvt, Set<StkStocksEntrees> stkStocksEntreeses, Set<StkStocksSorties> stkStocksSortieses) {
       this.comUnites = comUnites;
       this.stkArticles = stkArticles;
       this.stkMagasins = stkMagasins;
       this.commentaire = commentaire;
       this.dateBon = dateBon;
       this.numBonCde = numBonCde;
       this.numBonLiv = numBonLiv;
       this.numBonSti = numBonSti;
       this.pu = pu;
       this.qte = qte;
       this.typeMvt = typeMvt;
       this.stkStocksEntreeses = stkStocksEntreeses;
       this.stkStocksSortieses = stkStocksSortieses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="unite")
    public ComUnites getComUnites() {
        return this.comUnites;
    }
    
    public void setComUnites(ComUnites comUnites) {
        this.comUnites = comUnites;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="article")
    public StkArticles getStkArticles() {
        return this.stkArticles;
    }
    
    public void setStkArticles(StkArticles stkArticles) {
        this.stkArticles = stkArticles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="magasin")
    public StkMagasins getStkMagasins() {
        return this.stkMagasins;
    }
    
    public void setStkMagasins(StkMagasins stkMagasins) {
        this.stkMagasins = stkMagasins;
    }

    
    @Column(name="commentaire")
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_bon", length=10)
    public Date getDateBon() {
        return this.dateBon;
    }
    
    public void setDateBon(Date dateBon) {
        this.dateBon = dateBon;
    }

    
    @Column(name="num_bon_cde", length=20)
    public String getNumBonCde() {
        return this.numBonCde;
    }
    
    public void setNumBonCde(String numBonCde) {
        this.numBonCde = numBonCde;
    }

    
    @Column(name="num_bon_liv", length=20)
    public String getNumBonLiv() {
        return this.numBonLiv;
    }
    
    public void setNumBonLiv(String numBonLiv) {
        this.numBonLiv = numBonLiv;
    }

    
    @Column(name="num_bon_sti", length=20)
    public String getNumBonSti() {
        return this.numBonSti;
    }
    
    public void setNumBonSti(String numBonSti) {
        this.numBonSti = numBonSti;
    }

    
    @Column(name="pu", precision=22, scale=0)
    public Double getPu() {
        return this.pu;
    }
    
    public void setPu(Double pu) {
        this.pu = pu;
    }

    
    @Column(name="qte", precision=22, scale=0)
    public Double getQte() {
        return this.qte;
    }
    
    public void setQte(Double qte) {
        this.qte = qte;
    }

    
    @Column(name="type_mvt", length=2)
    public String getTypeMvt() {
        return this.typeMvt;
    }
    
    public void setTypeMvt(String typeMvt) {
        this.typeMvt = typeMvt;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkStocks")
    public Set<StkStocksEntrees> getStkStocksEntreeses() {
        return this.stkStocksEntreeses;
    }
    
    public void setStkStocksEntreeses(Set<StkStocksEntrees> stkStocksEntreeses) {
        this.stkStocksEntreeses = stkStocksEntreeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkStocks")
    public Set<StkStocksSorties> getStkStocksSortieses() {
        return this.stkStocksSortieses;
    }
    
    public void setStkStocksSortieses(Set<StkStocksSorties> stkStocksSortieses) {
        this.stkStocksSortieses = stkStocksSortieses;
    }




}


