package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComProfils generated by hbm2java
 */
@Entity
@Table(name="com_profils"
    ,catalog="ankata_db"
)
public class ComProfils  implements java.io.Serializable {


     private Long id;
     private Date dc;
     private Date du;
     private String estAdmin;
     private String etat;
     private String libelle;
     private String nature;
     private Long ucid;
     private Long uuid;
     private Set<ComRoles> comRoleses = new HashSet<ComRoles>(0);
     private Set<ComProfilsUsers> comProfilsUserses = new HashSet<ComProfilsUsers>(0);

    public ComProfils() {
    }

    public ComProfils(Date dc, Date du, String estAdmin, String etat, String libelle, String nature, Long ucid, Long uuid, Set<ComRoles> comRoleses, Set<ComProfilsUsers> comProfilsUserses) {
       this.dc = dc;
       this.du = du;
       this.estAdmin = estAdmin;
       this.etat = etat;
       this.libelle = libelle;
       this.nature = nature;
       this.ucid = ucid;
       this.uuid = uuid;
       this.comRoleses = comRoleses;
       this.comProfilsUserses = comProfilsUserses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dc", length=19)
    public Date getDc() {
        return this.dc;
    }
    
    public void setDc(Date dc) {
        this.dc = dc;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="du", length=19)
    public Date getDu() {
        return this.du;
    }
    
    public void setDu(Date du) {
        this.du = du;
    }

    
    @Column(name="est_admin", length=4)
    public String getEstAdmin() {
        return this.estAdmin;
    }
    
    public void setEstAdmin(String estAdmin) {
        this.estAdmin = estAdmin;
    }

    
    @Column(name="etat", length=4)
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }

    
    @Column(name="libelle")
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="nature", length=50)
    public String getNature() {
        return this.nature;
    }
    
    public void setNature(String nature) {
        this.nature = nature;
    }

    
    @Column(name="ucid")
    public Long getUcid() {
        return this.ucid;
    }
    
    public void setUcid(Long ucid) {
        this.ucid = ucid;
    }

    
    @Column(name="uuid")
    public Long getUuid() {
        return this.uuid;
    }
    
    public void setUuid(Long uuid) {
        this.uuid = uuid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comProfils")
    public Set<ComRoles> getComRoleses() {
        return this.comRoleses;
    }
    
    public void setComRoleses(Set<ComRoles> comRoleses) {
        this.comRoleses = comRoleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="comProfils")
    public Set<ComProfilsUsers> getComProfilsUserses() {
        return this.comProfilsUserses;
    }
    
    public void setComProfilsUserses(Set<ComProfilsUsers> comProfilsUserses) {
        this.comProfilsUserses = comProfilsUserses;
    }




}


