package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FltModeles generated by hbm2java
 */
@Entity
@Table(name="flt_modeles"
    ,catalog="ankata_db"
)
public class FltModeles  implements java.io.Serializable {


     private Long id;
     private FltMarques fltMarques;
     private Long categorie;
     private Long confort;
     private String gamme;
     private String nom;
     private String statut;
     private Set<FltTrajetsDetails> fltTrajetsDetailses = new HashSet<FltTrajetsDetails>(0);
     private Set<FltVehicules> fltVehiculeses = new HashSet<FltVehicules>(0);

    public FltModeles() {
    }

    public FltModeles(FltMarques fltMarques, Long categorie, Long confort, String gamme, String nom, String statut, Set<FltTrajetsDetails> fltTrajetsDetailses, Set<FltVehicules> fltVehiculeses) {
       this.fltMarques = fltMarques;
       this.categorie = categorie;
       this.confort = confort;
       this.gamme = gamme;
       this.nom = nom;
       this.statut = statut;
       this.fltTrajetsDetailses = fltTrajetsDetailses;
       this.fltVehiculeses = fltVehiculeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="marque")
    public FltMarques getFltMarques() {
        return this.fltMarques;
    }
    
    public void setFltMarques(FltMarques fltMarques) {
        this.fltMarques = fltMarques;
    }

    
    @Column(name="categorie")
    public Long getCategorie() {
        return this.categorie;
    }
    
    public void setCategorie(Long categorie) {
        this.categorie = categorie;
    }

    
    @Column(name="confort")
    public Long getConfort() {
        return this.confort;
    }
    
    public void setConfort(Long confort) {
        this.confort = confort;
    }

    
    @Column(name="gamme", length=20)
    public String getGamme() {
        return this.gamme;
    }
    
    public void setGamme(String gamme) {
        this.gamme = gamme;
    }

    
    @Column(name="nom", length=250)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="statut", length=2)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltModeles")
    public Set<FltTrajetsDetails> getFltTrajetsDetailses() {
        return this.fltTrajetsDetailses;
    }
    
    public void setFltTrajetsDetailses(Set<FltTrajetsDetails> fltTrajetsDetailses) {
        this.fltTrajetsDetailses = fltTrajetsDetailses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltModeles")
    public Set<FltVehicules> getFltVehiculeses() {
        return this.fltVehiculeses;
    }
    
    public void setFltVehiculeses(Set<FltVehicules> fltVehiculeses) {
        this.fltVehiculeses = fltVehiculeses;
    }




}


