package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComFournisseurs;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FltMissionsEntretiens generated by hbm2java
 */
@Entity
@Table(name="flt_missions_entretiens"
    ,catalog="ankata_db"
)
public class FltMissionsEntretiens  implements java.io.Serializable {


     private Long id;
     private ComFournisseurs comFournisseurs;
     private FltMissions fltMissions;
     private FltTypesEntretiens fltTypesEntretiens;
     private Date dateEnt;
     private String garage;
     private String mecano;
     private Double montant;
     private String observation;

    public FltMissionsEntretiens() {
    }

    public FltMissionsEntretiens(ComFournisseurs comFournisseurs, FltMissions fltMissions, FltTypesEntretiens fltTypesEntretiens, Date dateEnt, String garage, String mecano, Double montant, String observation) {
       this.comFournisseurs = comFournisseurs;
       this.fltMissions = fltMissions;
       this.fltTypesEntretiens = fltTypesEntretiens;
       this.dateEnt = dateEnt;
       this.garage = garage;
       this.mecano = mecano;
       this.montant = montant;
       this.observation = observation;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="founisseur")
    public ComFournisseurs getComFournisseurs() {
        return this.comFournisseurs;
    }
    
    public void setComFournisseurs(ComFournisseurs comFournisseurs) {
        this.comFournisseurs = comFournisseurs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mission")
    public FltMissions getFltMissions() {
        return this.fltMissions;
    }
    
    public void setFltMissions(FltMissions fltMissions) {
        this.fltMissions = fltMissions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_ent")
    public FltTypesEntretiens getFltTypesEntretiens() {
        return this.fltTypesEntretiens;
    }
    
    public void setFltTypesEntretiens(FltTypesEntretiens fltTypesEntretiens) {
        this.fltTypesEntretiens = fltTypesEntretiens;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_ent", length=10)
    public Date getDateEnt() {
        return this.dateEnt;
    }
    
    public void setDateEnt(Date dateEnt) {
        this.dateEnt = dateEnt;
    }

    
    @Column(name="garage", length=200)
    public String getGarage() {
        return this.garage;
    }
    
    public void setGarage(String garage) {
        this.garage = garage;
    }

    
    @Column(name="mecano", length=200)
    public String getMecano() {
        return this.mecano;
    }
    
    public void setMecano(String mecano) {
        this.mecano = mecano;
    }

    
    @Column(name="montant", precision=22, scale=0)
    public Double getMontant() {
        return this.montant;
    }
    
    public void setMontant(Double montant) {
        this.montant = montant;
    }

    
    @Column(name="observation")
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }




}


