package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComPisteAudit generated by hbm2java
 */
@Entity
@Table(name="com_piste_audit"
    ,catalog="ankata_db"
)
public class ComPisteAudit  implements java.io.Serializable {


     private Long id;
     private ComUsers comUsers;
     private String action;
     private Date date;
     private String description;
     private String fonctionnalite;
     private String newdata;
     private String olddata;

    public ComPisteAudit() {
    }

    public ComPisteAudit(ComUsers comUsers, String action, Date date, String description, String fonctionnalite, String newdata, String olddata) {
       this.comUsers = comUsers;
       this.action = action;
       this.date = date;
       this.description = description;
       this.fonctionnalite = fonctionnalite;
       this.newdata = newdata;
       this.olddata = olddata;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user")
    public ComUsers getComUsers() {
        return this.comUsers;
    }
    
    public void setComUsers(ComUsers comUsers) {
        this.comUsers = comUsers;
    }

    
    @Column(name="action", length=50)
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="fonctionnalite", length=100)
    public String getFonctionnalite() {
        return this.fonctionnalite;
    }
    
    public void setFonctionnalite(String fonctionnalite) {
        this.fonctionnalite = fonctionnalite;
    }

    
    @Column(name="newdata")
    public String getNewdata() {
        return this.newdata;
    }
    
    public void setNewdata(String newdata) {
        this.newdata = newdata;
    }

    
    @Column(name="olddata")
    public String getOlddata() {
        return this.olddata;
    }
    
    public void setOlddata(String olddata) {
        this.olddata = olddata;
    }




}


