package com.horus.ankata.core.domain.vente;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.flotte.FltMissions;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VteBonsLivraisons generated by hbm2java
 */
@Entity
@Table(name="vte_bons_livraisons"
    ,catalog="ankata_db"
)
public class VteBonsLivraisons  implements java.io.Serializable {


     private Long id;
     private FltMissions fltMissions;
     private Date dateAnnule;
     private Date dateFacture;
     private Date dateLivraison;
     private Date dateRelance;
     private Date dateValide;
     private Date dateValidite;
     private Integer etat;
     private Boolean exoTva;
     private Boolean gele;
     private String motif;
     private String motifAnnule;
     private String numBon;
     private String numFacture;
     private String observation;
     private Boolean solde;
     private Double totHt;
     private Double totRabais;
     private Double totReg;
     private Double totRemise;
     private Double totTtc;
     private Double totTva;
     private Set<VteBonsLivraisonsLignes> vteBonsLivraisonsLigneses = new HashSet<VteBonsLivraisonsLignes>(0);

    public VteBonsLivraisons() {
    }

    public VteBonsLivraisons(FltMissions fltMissions, Date dateAnnule, Date dateFacture, Date dateLivraison, Date dateRelance, Date dateValide, Date dateValidite, Integer etat, Boolean exoTva, Boolean gele, String motif, String motifAnnule, String numBon, String numFacture, String observation, Boolean solde, Double totHt, Double totRabais, Double totReg, Double totRemise, Double totTtc, Double totTva, Set<VteBonsLivraisonsLignes> vteBonsLivraisonsLigneses) {
       this.fltMissions = fltMissions;
       this.dateAnnule = dateAnnule;
       this.dateFacture = dateFacture;
       this.dateLivraison = dateLivraison;
       this.dateRelance = dateRelance;
       this.dateValide = dateValide;
       this.dateValidite = dateValidite;
       this.etat = etat;
       this.exoTva = exoTva;
       this.gele = gele;
       this.motif = motif;
       this.motifAnnule = motifAnnule;
       this.numBon = numBon;
       this.numFacture = numFacture;
       this.observation = observation;
       this.solde = solde;
       this.totHt = totHt;
       this.totRabais = totRabais;
       this.totReg = totReg;
       this.totRemise = totRemise;
       this.totTtc = totTtc;
       this.totTva = totTva;
       this.vteBonsLivraisonsLigneses = vteBonsLivraisonsLigneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="mission")
    public FltMissions getFltMissions() {
        return this.fltMissions;
    }
    
    public void setFltMissions(FltMissions fltMissions) {
        this.fltMissions = fltMissions;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_annule", length=10)
    public Date getDateAnnule() {
        return this.dateAnnule;
    }
    
    public void setDateAnnule(Date dateAnnule) {
        this.dateAnnule = dateAnnule;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_facture", length=10)
    public Date getDateFacture() {
        return this.dateFacture;
    }
    
    public void setDateFacture(Date dateFacture) {
        this.dateFacture = dateFacture;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_livraison", length=10)
    public Date getDateLivraison() {
        return this.dateLivraison;
    }
    
    public void setDateLivraison(Date dateLivraison) {
        this.dateLivraison = dateLivraison;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_relance", length=10)
    public Date getDateRelance() {
        return this.dateRelance;
    }
    
    public void setDateRelance(Date dateRelance) {
        this.dateRelance = dateRelance;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_valide", length=10)
    public Date getDateValide() {
        return this.dateValide;
    }
    
    public void setDateValide(Date dateValide) {
        this.dateValide = dateValide;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_validite", length=10)
    public Date getDateValidite() {
        return this.dateValidite;
    }
    
    public void setDateValidite(Date dateValidite) {
        this.dateValidite = dateValidite;
    }

    
    @Column(name="etat")
    public Integer getEtat() {
        return this.etat;
    }
    
    public void setEtat(Integer etat) {
        this.etat = etat;
    }

    
    @Column(name="exo_tva")
    public Boolean getExoTva() {
        return this.exoTva;
    }
    
    public void setExoTva(Boolean exoTva) {
        this.exoTva = exoTva;
    }

    
    @Column(name="gele")
    public Boolean getGele() {
        return this.gele;
    }
    
    public void setGele(Boolean gele) {
        this.gele = gele;
    }

    
    @Column(name="motif", length=300)
    public String getMotif() {
        return this.motif;
    }
    
    public void setMotif(String motif) {
        this.motif = motif;
    }

    
    @Column(name="motif_annule", length=200)
    public String getMotifAnnule() {
        return this.motifAnnule;
    }
    
    public void setMotifAnnule(String motifAnnule) {
        this.motifAnnule = motifAnnule;
    }

    
    @Column(name="num_bon", length=20)
    public String getNumBon() {
        return this.numBon;
    }
    
    public void setNumBon(String numBon) {
        this.numBon = numBon;
    }

    
    @Column(name="num_facture", length=20)
    public String getNumFacture() {
        return this.numFacture;
    }
    
    public void setNumFacture(String numFacture) {
        this.numFacture = numFacture;
    }

    
    @Column(name="observation", length=500)
    public String getObservation() {
        return this.observation;
    }
    
    public void setObservation(String observation) {
        this.observation = observation;
    }

    
    @Column(name="solde")
    public Boolean getSolde() {
        return this.solde;
    }
    
    public void setSolde(Boolean solde) {
        this.solde = solde;
    }

    
    @Column(name="tot_ht", precision=22, scale=0)
    public Double getTotHt() {
        return this.totHt;
    }
    
    public void setTotHt(Double totHt) {
        this.totHt = totHt;
    }

    
    @Column(name="tot_rabais", precision=22, scale=0)
    public Double getTotRabais() {
        return this.totRabais;
    }
    
    public void setTotRabais(Double totRabais) {
        this.totRabais = totRabais;
    }

    
    @Column(name="tot_reg", precision=22, scale=0)
    public Double getTotReg() {
        return this.totReg;
    }
    
    public void setTotReg(Double totReg) {
        this.totReg = totReg;
    }

    
    @Column(name="tot_remise", precision=22, scale=0)
    public Double getTotRemise() {
        return this.totRemise;
    }
    
    public void setTotRemise(Double totRemise) {
        this.totRemise = totRemise;
    }

    
    @Column(name="tot_ttc", precision=22, scale=0)
    public Double getTotTtc() {
        return this.totTtc;
    }
    
    public void setTotTtc(Double totTtc) {
        this.totTtc = totTtc;
    }

    
    @Column(name="tot_tva", precision=22, scale=0)
    public Double getTotTva() {
        return this.totTva;
    }
    
    public void setTotTva(Double totTva) {
        this.totTva = totTva;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vteBonsLivraisons")
    public Set<VteBonsLivraisonsLignes> getVteBonsLivraisonsLigneses() {
        return this.vteBonsLivraisonsLigneses;
    }
    
    public void setVteBonsLivraisonsLigneses(Set<VteBonsLivraisonsLignes> vteBonsLivraisonsLigneses) {
        this.vteBonsLivraisonsLigneses = vteBonsLivraisonsLigneses;
    }




}


