package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StkMagasinsArticles generated by hbm2java
 */
@Entity
@Table(name="stk_magasins_articles"
    ,catalog="ankata_db"
)
public class StkMagasinsArticles  implements java.io.Serializable {


     private Long id;
     private StkArticles stkArticles;
     private StkMagasins stkMagasins;
     private Double pump;
     private Double qteDispo;
     private Double qteEntree;
     private Double qteReelle;
     private Double qteSortie;

    public StkMagasinsArticles() {
    }

    public StkMagasinsArticles(StkArticles stkArticles, StkMagasins stkMagasins, Double pump, Double qteDispo, Double qteEntree, Double qteReelle, Double qteSortie) {
       this.stkArticles = stkArticles;
       this.stkMagasins = stkMagasins;
       this.pump = pump;
       this.qteDispo = qteDispo;
       this.qteEntree = qteEntree;
       this.qteReelle = qteReelle;
       this.qteSortie = qteSortie;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="article")
    public StkArticles getStkArticles() {
        return this.stkArticles;
    }
    
    public void setStkArticles(StkArticles stkArticles) {
        this.stkArticles = stkArticles;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="magasin")
    public StkMagasins getStkMagasins() {
        return this.stkMagasins;
    }
    
    public void setStkMagasins(StkMagasins stkMagasins) {
        this.stkMagasins = stkMagasins;
    }

    
    @Column(name="pump", precision=22, scale=0)
    public Double getPump() {
        return this.pump;
    }
    
    public void setPump(Double pump) {
        this.pump = pump;
    }

    
    @Column(name="qte_dispo", precision=22, scale=0)
    public Double getQteDispo() {
        return this.qteDispo;
    }
    
    public void setQteDispo(Double qteDispo) {
        this.qteDispo = qteDispo;
    }

    
    @Column(name="qte_entree", precision=22, scale=0)
    public Double getQteEntree() {
        return this.qteEntree;
    }
    
    public void setQteEntree(Double qteEntree) {
        this.qteEntree = qteEntree;
    }

    
    @Column(name="qte_reelle", precision=22, scale=0)
    public Double getQteReelle() {
        return this.qteReelle;
    }
    
    public void setQteReelle(Double qteReelle) {
        this.qteReelle = qteReelle;
    }

    
    @Column(name="qte_sortie", precision=22, scale=0)
    public Double getQteSortie() {
        return this.qteSortie;
    }
    
    public void setQteSortie(Double qteSortie) {
        this.qteSortie = qteSortie;
    }




}


