package com.horus.ankata.core.domain.flotte;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FltRemorques generated by hbm2java
 */
@Entity
@Table(name="flt_remorques"
    ,catalog="ankata_db"
)
public class FltRemorques  implements java.io.Serializable {


     private Long id;
     private FltAcquisitions fltAcquisitions;
     private FltParcs fltParcs;
     private String code;
     private String couleur;
     private Date dateEntreeParc;
     private String immatriculation;
     private String numCarteGrise;
     private String numChassis;
     private String numOrdre;
     private Set<FltMissions> fltMissionses = new HashSet<FltMissions>(0);

    public FltRemorques() {
    }

    public FltRemorques(FltAcquisitions fltAcquisitions, FltParcs fltParcs, String code, String couleur, Date dateEntreeParc, String immatriculation, String numCarteGrise, String numChassis, String numOrdre, Set<FltMissions> fltMissionses) {
       this.fltAcquisitions = fltAcquisitions;
       this.fltParcs = fltParcs;
       this.code = code;
       this.couleur = couleur;
       this.dateEntreeParc = dateEntreeParc;
       this.immatriculation = immatriculation;
       this.numCarteGrise = numCarteGrise;
       this.numChassis = numChassis;
       this.numOrdre = numOrdre;
       this.fltMissionses = fltMissionses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="acquisition")
    public FltAcquisitions getFltAcquisitions() {
        return this.fltAcquisitions;
    }
    
    public void setFltAcquisitions(FltAcquisitions fltAcquisitions) {
        this.fltAcquisitions = fltAcquisitions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="parc")
    public FltParcs getFltParcs() {
        return this.fltParcs;
    }
    
    public void setFltParcs(FltParcs fltParcs) {
        this.fltParcs = fltParcs;
    }

    
    @Column(name="code", length=20)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    
    @Column(name="couleur", length=20)
    public String getCouleur() {
        return this.couleur;
    }
    
    public void setCouleur(String couleur) {
        this.couleur = couleur;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_entree_parc", length=10)
    public Date getDateEntreeParc() {
        return this.dateEntreeParc;
    }
    
    public void setDateEntreeParc(Date dateEntreeParc) {
        this.dateEntreeParc = dateEntreeParc;
    }

    
    @Column(name="immatriculation", length=50)
    public String getImmatriculation() {
        return this.immatriculation;
    }
    
    public void setImmatriculation(String immatriculation) {
        this.immatriculation = immatriculation;
    }

    
    @Column(name="num_carte_grise", length=50)
    public String getNumCarteGrise() {
        return this.numCarteGrise;
    }
    
    public void setNumCarteGrise(String numCarteGrise) {
        this.numCarteGrise = numCarteGrise;
    }

    
    @Column(name="num_chassis", length=20)
    public String getNumChassis() {
        return this.numChassis;
    }
    
    public void setNumChassis(String numChassis) {
        this.numChassis = numChassis;
    }

    
    @Column(name="num_ordre", length=20)
    public String getNumOrdre() {
        return this.numOrdre;
    }
    
    public void setNumOrdre(String numOrdre) {
        this.numOrdre = numOrdre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fltRemorques")
    public Set<FltMissions> getFltMissionses() {
        return this.fltMissionses;
    }
    
    public void setFltMissionses(Set<FltMissions> fltMissionses) {
        this.fltMissionses = fltMissionses;
    }




}


