package com.horus.ankata.core.domain.achat;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComFournisseurs;
import com.horus.ankata.core.domain.stock.StkMagasins;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AchBonsLivraisons generated by hbm2java
 */
@Entity
@Table(name="ach_bons_livraisons"
    ,catalog="ankata_db"
)
public class AchBonsLivraisons  implements java.io.Serializable {


     private Long id;
     private AchBonsCommandes achBonsCommandes;
     private ComFournisseurs comFournisseurs;
     private StkMagasins stkMagasins;
     private Date dateBon;
     private String description;
     private Integer etat;
     private Double montantHt;
     private Double montantTtc;
     private Double montantTva;
     private String numBon;
     private String refFrs;
     private Double tva;
     private Set<AchBonsLivraisonsLignes> achBonsLivraisonsLigneses = new HashSet<AchBonsLivraisonsLignes>(0);

    public AchBonsLivraisons() {
    }

    public AchBonsLivraisons(AchBonsCommandes achBonsCommandes, ComFournisseurs comFournisseurs, StkMagasins stkMagasins, Date dateBon, String description, Integer etat, Double montantHt, Double montantTtc, Double montantTva, String numBon, String refFrs, Double tva, Set<AchBonsLivraisonsLignes> achBonsLivraisonsLigneses) {
       this.achBonsCommandes = achBonsCommandes;
       this.comFournisseurs = comFournisseurs;
       this.stkMagasins = stkMagasins;
       this.dateBon = dateBon;
       this.description = description;
       this.etat = etat;
       this.montantHt = montantHt;
       this.montantTtc = montantTtc;
       this.montantTva = montantTva;
       this.numBon = numBon;
       this.refFrs = refFrs;
       this.tva = tva;
       this.achBonsLivraisonsLigneses = achBonsLivraisonsLigneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="bon_commande")
    public AchBonsCommandes getAchBonsCommandes() {
        return this.achBonsCommandes;
    }
    
    public void setAchBonsCommandes(AchBonsCommandes achBonsCommandes) {
        this.achBonsCommandes = achBonsCommandes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="founisseur")
    public ComFournisseurs getComFournisseurs() {
        return this.comFournisseurs;
    }
    
    public void setComFournisseurs(ComFournisseurs comFournisseurs) {
        this.comFournisseurs = comFournisseurs;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="magasin")
    public StkMagasins getStkMagasins() {
        return this.stkMagasins;
    }
    
    public void setStkMagasins(StkMagasins stkMagasins) {
        this.stkMagasins = stkMagasins;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_bon", length=10)
    public Date getDateBon() {
        return this.dateBon;
    }
    
    public void setDateBon(Date dateBon) {
        this.dateBon = dateBon;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="etat")
    public Integer getEtat() {
        return this.etat;
    }
    
    public void setEtat(Integer etat) {
        this.etat = etat;
    }

    
    @Column(name="montant_ht", precision=22, scale=0)
    public Double getMontantHt() {
        return this.montantHt;
    }
    
    public void setMontantHt(Double montantHt) {
        this.montantHt = montantHt;
    }

    
    @Column(name="montant_ttc", precision=22, scale=0)
    public Double getMontantTtc() {
        return this.montantTtc;
    }
    
    public void setMontantTtc(Double montantTtc) {
        this.montantTtc = montantTtc;
    }

    
    @Column(name="montant_tva", precision=22, scale=0)
    public Double getMontantTva() {
        return this.montantTva;
    }
    
    public void setMontantTva(Double montantTva) {
        this.montantTva = montantTva;
    }

    
    @Column(name="num_bon", length=20)
    public String getNumBon() {
        return this.numBon;
    }
    
    public void setNumBon(String numBon) {
        this.numBon = numBon;
    }

    
    @Column(name="ref_frs", length=20)
    public String getRefFrs() {
        return this.refFrs;
    }
    
    public void setRefFrs(String refFrs) {
        this.refFrs = refFrs;
    }

    
    @Column(name="tva", precision=22, scale=0)
    public Double getTva() {
        return this.tva;
    }
    
    public void setTva(Double tva) {
        this.tva = tva;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="achBonsLivraisons")
    public Set<AchBonsLivraisonsLignes> getAchBonsLivraisonsLigneses() {
        return this.achBonsLivraisonsLigneses;
    }
    
    public void setAchBonsLivraisonsLigneses(Set<AchBonsLivraisonsLignes> achBonsLivraisonsLigneses) {
        this.achBonsLivraisonsLigneses = achBonsLivraisonsLigneses;
    }




}


