package com.horus.ankata.core.domain.achat;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import com.horus.ankata.core.domain.commons.ComFournisseurs;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AchDevis generated by hbm2java
 */
@Entity
@Table(name="ach_devis"
    ,catalog="ankata_db"
)
public class AchDevis  implements java.io.Serializable {


     private Long id;
     private AchDemandes achDemandes;
     private ComFournisseurs comFournisseurs;
     private Date dateDevis;
     private String description;
     private Integer etat;
     private Double montantHt;
     private Double montantTtc;
     private Double montantTva;
     private String numDevis;
     private String numDevisFrn;
     private Double tva;
     private Set<AchDevisLignes> achDevisLigneses = new HashSet<AchDevisLignes>(0);
     private Set<AchBonsCommandes> achBonsCommandeses = new HashSet<AchBonsCommandes>(0);

    public AchDevis() {
    }

    public AchDevis(AchDemandes achDemandes, ComFournisseurs comFournisseurs, Date dateDevis, String description, Integer etat, Double montantHt, Double montantTtc, Double montantTva, String numDevis, String numDevisFrn, Double tva, Set<AchDevisLignes> achDevisLigneses, Set<AchBonsCommandes> achBonsCommandeses) {
       this.achDemandes = achDemandes;
       this.comFournisseurs = comFournisseurs;
       this.dateDevis = dateDevis;
       this.description = description;
       this.etat = etat;
       this.montantHt = montantHt;
       this.montantTtc = montantTtc;
       this.montantTva = montantTva;
       this.numDevis = numDevis;
       this.numDevisFrn = numDevisFrn;
       this.tva = tva;
       this.achDevisLigneses = achDevisLigneses;
       this.achBonsCommandeses = achBonsCommandeses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="demande")
    public AchDemandes getAchDemandes() {
        return this.achDemandes;
    }
    
    public void setAchDemandes(AchDemandes achDemandes) {
        this.achDemandes = achDemandes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="founisseur")
    public ComFournisseurs getComFournisseurs() {
        return this.comFournisseurs;
    }
    
    public void setComFournisseurs(ComFournisseurs comFournisseurs) {
        this.comFournisseurs = comFournisseurs;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_devis", length=10)
    public Date getDateDevis() {
        return this.dateDevis;
    }
    
    public void setDateDevis(Date dateDevis) {
        this.dateDevis = dateDevis;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="etat")
    public Integer getEtat() {
        return this.etat;
    }
    
    public void setEtat(Integer etat) {
        this.etat = etat;
    }

    
    @Column(name="montant_ht", precision=22, scale=0)
    public Double getMontantHt() {
        return this.montantHt;
    }
    
    public void setMontantHt(Double montantHt) {
        this.montantHt = montantHt;
    }

    
    @Column(name="montant_ttc", precision=22, scale=0)
    public Double getMontantTtc() {
        return this.montantTtc;
    }
    
    public void setMontantTtc(Double montantTtc) {
        this.montantTtc = montantTtc;
    }

    
    @Column(name="montant_tva", precision=22, scale=0)
    public Double getMontantTva() {
        return this.montantTva;
    }
    
    public void setMontantTva(Double montantTva) {
        this.montantTva = montantTva;
    }

    
    @Column(name="num_devis", length=20)
    public String getNumDevis() {
        return this.numDevis;
    }
    
    public void setNumDevis(String numDevis) {
        this.numDevis = numDevis;
    }

    
    @Column(name="num_devis_frn", length=20)
    public String getNumDevisFrn() {
        return this.numDevisFrn;
    }
    
    public void setNumDevisFrn(String numDevisFrn) {
        this.numDevisFrn = numDevisFrn;
    }

    
    @Column(name="tva", precision=22, scale=0)
    public Double getTva() {
        return this.tva;
    }
    
    public void setTva(Double tva) {
        this.tva = tva;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="achDevis")
    public Set<AchDevisLignes> getAchDevisLigneses() {
        return this.achDevisLigneses;
    }
    
    public void setAchDevisLigneses(Set<AchDevisLignes> achDevisLigneses) {
        this.achDevisLigneses = achDevisLigneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="achDevis")
    public Set<AchBonsCommandes> getAchBonsCommandeses() {
        return this.achBonsCommandeses;
    }
    
    public void setAchBonsCommandeses(Set<AchBonsCommandes> achBonsCommandeses) {
        this.achBonsCommandeses = achBonsCommandeses;
    }




}


