package com.horus.ankata.core.domain.achat;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AchDemandes generated by hbm2java
 */
@Entity
@Table(name="ach_demandes"
    ,catalog="ankata_db"
)
public class AchDemandes  implements java.io.Serializable {


     private Long id;
     private Date dateDemande;
     private String demandeur;
     private Integer etat;
     private String numDemande;
     private String objet;
     private Set<AchDemandesLignes> achDemandesLigneses = new HashSet<AchDemandesLignes>(0);
     private Set<AchDevis> achDevises = new HashSet<AchDevis>(0);

    public AchDemandes() {
    }

    public AchDemandes(Date dateDemande, String demandeur, Integer etat, String numDemande, String objet, Set<AchDemandesLignes> achDemandesLigneses, Set<AchDevis> achDevises) {
       this.dateDemande = dateDemande;
       this.demandeur = demandeur;
       this.etat = etat;
       this.numDemande = numDemande;
       this.objet = objet;
       this.achDemandesLigneses = achDemandesLigneses;
       this.achDevises = achDevises;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_demande", length=10)
    public Date getDateDemande() {
        return this.dateDemande;
    }
    
    public void setDateDemande(Date dateDemande) {
        this.dateDemande = dateDemande;
    }

    
    @Column(name="demandeur", length=200)
    public String getDemandeur() {
        return this.demandeur;
    }
    
    public void setDemandeur(String demandeur) {
        this.demandeur = demandeur;
    }

    
    @Column(name="etat")
    public Integer getEtat() {
        return this.etat;
    }
    
    public void setEtat(Integer etat) {
        this.etat = etat;
    }

    
    @Column(name="num_demande", length=20)
    public String getNumDemande() {
        return this.numDemande;
    }
    
    public void setNumDemande(String numDemande) {
        this.numDemande = numDemande;
    }

    
    @Column(name="objet", length=300)
    public String getObjet() {
        return this.objet;
    }
    
    public void setObjet(String objet) {
        this.objet = objet;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="achDemandes")
    public Set<AchDemandesLignes> getAchDemandesLigneses() {
        return this.achDemandesLigneses;
    }
    
    public void setAchDemandesLigneses(Set<AchDemandesLignes> achDemandesLigneses) {
        this.achDemandesLigneses = achDemandesLigneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="achDemandes")
    public Set<AchDevis> getAchDevises() {
        return this.achDevises;
    }
    
    public void setAchDevises(Set<AchDevis> achDevises) {
        this.achDevises = achDevises;
    }




}


