package com.horus.ankata.core.domain.stock;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StkInventaires generated by hbm2java
 */
@Entity
@Table(name="stk_inventaires"
    ,catalog="ankata_db"
)
public class StkInventaires  implements java.io.Serializable {


     private Long id;
     private StkMagasins stkMagasins;
     private Date dateDebut;
     private Date dateFin;
     private Integer etat;
     private Integer modeInv;
     private String numero;
     private Long personne;
     private Set<StkInventairesLignes> stkInventairesLigneses = new HashSet<StkInventairesLignes>(0);

    public StkInventaires() {
    }

    public StkInventaires(StkMagasins stkMagasins, Date dateDebut, Date dateFin, Integer etat, Integer modeInv, String numero, Long personne, Set<StkInventairesLignes> stkInventairesLigneses) {
       this.stkMagasins = stkMagasins;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.etat = etat;
       this.modeInv = modeInv;
       this.numero = numero;
       this.personne = personne;
       this.stkInventairesLigneses = stkInventairesLigneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="magasin")
    public StkMagasins getStkMagasins() {
        return this.stkMagasins;
    }
    
    public void setStkMagasins(StkMagasins stkMagasins) {
        this.stkMagasins = stkMagasins;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_debut", length=19)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_fin", length=19)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    
    @Column(name="etat")
    public Integer getEtat() {
        return this.etat;
    }
    
    public void setEtat(Integer etat) {
        this.etat = etat;
    }

    
    @Column(name="mode_inv")
    public Integer getModeInv() {
        return this.modeInv;
    }
    
    public void setModeInv(Integer modeInv) {
        this.modeInv = modeInv;
    }

    
    @Column(name="numero", length=20)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="personne")
    public Long getPersonne() {
        return this.personne;
    }
    
    public void setPersonne(Long personne) {
        this.personne = personne;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="stkInventaires")
    public Set<StkInventairesLignes> getStkInventairesLigneses() {
        return this.stkInventairesLigneses;
    }
    
    public void setStkInventairesLigneses(Set<StkInventairesLignes> stkInventairesLigneses) {
        this.stkInventairesLigneses = stkInventairesLigneses;
    }




}


