package com.horus.ankata.core.domain.commons;
// Generated 25 oct. 2017 16:01:11 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComRoles generated by hbm2java
 */
@Entity
@Table(name="com_roles"
    ,catalog="ankata_db"
)
public class ComRoles  implements java.io.Serializable {


     private Long id;
     private ComMenus comMenus;
     private ComProfils comProfils;

    public ComRoles() {
    }

    public ComRoles(ComMenus comMenus, ComProfils comProfils) {
       this.comMenus = comMenus;
       this.comProfils = comProfils;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="menus")
    public ComMenus getComMenus() {
        return this.comMenus;
    }
    
    public void setComMenus(ComMenus comMenus) {
        this.comMenus = comMenus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profil")
    public ComProfils getComProfils() {
        return this.comProfils;
    }
    
    public void setComProfils(ComProfils comProfils) {
        this.comProfils = comProfils;
    }




}


